### PR TITLE
Tackle Rails 5.2.2 support

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
I'm guessing we'll probably need to bump the minimum ransack dependency.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
I propose to bump the minimum ransack dependency to ensure activeadmin always works under rails 5.2.2. This can be solved manually by end users by updating `ransack`, but I think this might be better? Thoughts @activeadmin/maintainers?

**Comment by javierjulio** [comment]
@deivid-rodriguez I think that's best. It's been painless to update too. We haven't had issues. This would also mitigate issues reported here when all that's needed is to update ransack. I think its good we keep updating our minimum requirements as we do more releases. 👍🏻

**Comment by deivid-rodriguez** [comment]
Ok!

**Comment by nicolas-brousse** [comment]
Any idea of when this will be released?

**Comment by deivid-rodriguez** [comment]
No, sorry. But you can run `bundle update ransack` and you should be fine.

**Comment by nicolas-brousse** [comment]
My bad I though version was locked with the current version of ActiveAdmin. Thanks for your answer.

**Pull request merged**
