### PR TITLE
Search Status Sidebar - Use Model Names Rather Than ID

### PR DESCRIPTION
**Pull request by ccallebs**
I just fixed merge conflicts for activeadmin/activeadmin#3902. Any other fixes will go in this branch.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
@ccallebs If you had edit privileges in the contributor's branch, it would be nice to fix the conflicts there to keep the discussion in one place. It seems that there was a lot of discussion.

**Comment by ccallebs** [comment]
@deivid-rodriguez My apologies, but not quite sure how to modify his branch in place. Could you point me toward a resource?

**Comment by deivid-rodriguez** [comment]
@ccallebs I think I've never modified a contributor's branch but my understanding is that you can just checkout out the branch and push to it. If you have permissions, it will let you do it, otherwise it will error out.

I think @varyonic rebased some very old branches at some point so he might have better info? How does the "Allow edits from maintainers" setting behaves in branches created before the setting was added?

**Comment by varyonic** [comment]
I don't think Chuck has access for that, don't worry about it.

**Comment by deivid-rodriguez** [comment]
Ah ok. Sorry then @ccallebs, forget what I said... :pray:

**Comment by ccallebs** [comment]
@deivid-rodriguez I've been trying to fix the specs, but have been able to run them locally. I keep getting the following:

```
activeadmin git/master
❯ bundle exec rake test

The git source https://github.com/DatabaseCleaner/database_cleaner.git is not yet checked out. Please run `bundle install` before trying to start your application
```
I've of course ran "bundle install" and "gem list" produces the following:

```
activeadmin git/master
❯ gem list | grep database_cleaner
database_cleaner (1.5.3)
```

Am I missing something?

**Comment by deivid-rodriguez** [comment]
Can you follow the steps in https://github.com/activeadmin/activeadmin/blob/master/CONTRIBUTING.md#3-get-the-test-suite-running. Let me know if you run into any problems.

**Comment by ccallebs** [comment]
@deivid-rodriguez Working now, I had mucked up the steps. Will take another stab tomorrow. Thanks!

**Comment by ccallebs** [comment]
@Fivell Closing this -- I unfortunately don't have the time right now to finish this up. Best of luck!

**Pull request closed without merging**
