### PR TITLE
Try to fix stuck codeclimate coverage checks

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
The problem seems to be that codeclimate's test-reporter doesn't support Github Actions. See https://github.com/codeclimate/test-reporter/issues/406.

However, there's this action that claims to set the proper environment variables needed for codeclimate to calculate diff coverage.

So let's try it!

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
It worked!! :tada:

**Comment by deivid-rodriguez** [comment]
I'm going to make another check though by creating a PR from my personal activeadmin fork to see if it works from there too (last time I had problems with that).

**Comment by deivid-rodriguez** [comment]
Created [a PR from my personal fork](https://github.com/activeadmin/activeadmin/pull/6581) rebased on top of this one and it worked too, so it seems all fine! :tada:

**Comment by javierjulio** [comment]
Awesome thanks! I take it we want to get this in first so I'll review now.

**Review by javierjulio — APPROVED** [review]
Thanks! 🙌🏻

**Pull request merged**
