### PR TITLE
Cut 2.0.0.rc1

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
Let's release a first rc for activeadmin 2.0!

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
On it!

**Comment by deivid-rodriguez** [comment]
2.0.0.rc1 is out!

**Comment by javierjulio** [comment]
Awesome thanks so much for getting that out David! 👏🏻❤️

**Comment by deivid-rodriguez** [comment]
Thanks to you too for all your work!

**Pull request merged**
