### PR TITLE
Tidelift banner

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
This is some initial work on the Tidelfit banner

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
This is the initial version

initial

This is with a few extra tweaks I added

second

Ok with the second version?

**Comment by deivid-rodriguez** [comment]
Removed WIP. Pending ok to the last screenshot, I'll then cleanup commit history and wait for a final approval. I have no experience deploying to github sites, I made a few local tweaks to setup the development environment, but I don't think they should affect the deploy?

**Comment by deivid-rodriguez** [comment]
Ok, let's see how this deploy goes!

**Comment by javierjulio** [comment]
Awesome! No problem at all. Well done. 👍🏻

**Pull request merged**
