### PR TITLE
Switch from CanCan to CanCanCan

### PR DESCRIPTION
**Pull request by coorasse**

### CODE REVIEW

**Comment by coorasse** [comment]
lol #5686

**Comment by deivid-rodriguez** [comment]
lol

**Comment by deivid-rodriguez** [comment]
Now they are both closed :rofl:

**Comment by coorasse** [comment]
I can't stop laughing 🤣🤣🤣

**Comment by deivid-rodriguez** [comment]
Me neither :rofl: :rofl:

**Comment by javierjulio** [comment]
Awesome thanks you two! 😂👌🏻

**Pull request merged**
