### PR TITLE
Fix some test tasks under some conditions

### LINKED ISSUE #5018: BUNDLE_GEMFILE not set by default
The [document](https://github.com/activeadmin/activeadmin/blob/master/CONTRIBUTING.md) says  `This will automatically run the tests against Rails 5.0` but it does not seem to work?

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
* Fixes `bundle exec rake test` task without `BUNDLE_GEMFILE` explicitly set.
* Fixes `bundle exec rake` and `bundle exec rake test` without `BUNDLE_GEMFILE` explicitly set when dependencies not installed.

Fixes #5018.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
@wesley6j Could you try this out and see if it works for you?

**Comment by wesley6j** [comment]
@deivid-rodriguez It works! It is nice that `bundle exec rake` takes care of missing gems now. 

The current process is perfect: `bundle install` installs `rake` -> `bundle exec rake` installs all dependencies.

**Comment by deivid-rodriguez** [comment]
Well, actually now I broke the `test_all` task... :disappointed:

I'm actually considering to make the `export BUNDLE_GEMFILE=...` step explicit in the CONTRIBUTING instructions and remove all the magic. We could add a link to [direnv](https://github.com/direnv/direnv) or something for folks who work daily on this code base and want to automatize the development environment a bit more.

@varyonic @Fivell @javierjulio @timoschilling Are you ok with that? This is one more step for contributors to get set up, but it's more bullet proof and it means we need to maintain less magic that it's likely to break.

**Comment by deivid-rodriguez** [comment]
Went ahead and removed a lot of the magic. I ended up not mentioning https://github.com/direnv/direnv, but it could be added somewhere.

**Comment by deivid-rodriguez** [comment]
Fixed a couple of typos and force-pushed.

**Pull request merged**
