### PR TITLE
FIX comments migration. Now using resource as references

### PR DESCRIPTION
**Pull request by krim**
In base case migration used a separated resource_id and resource_type. And resource_id was a STRING type column. It's terrible.
Now we will use normal references for resource such as author.

### CODE REVIEW

**Comment by Fivell** [comment]
@varyonic, did you see why it was introduced? Take a look pls https://github.com/activeadmin/activeadmin/issues/34

**Comment by Fivell** [comment]
even there is line in changelog about this https://github.com/activeadmin/activeadmin/blob/0-6-stable/CHANGELOG.md#bug-fixes-3

**Comment by varyonic** [comment]
We should have had a test failure?

**Comment by Fivell** [comment]
@varyonic , looks like yes but they doesn't work as expected

https://github.com/activeadmin/activeadmin/blob/d01155f73a0e2cc27d712792270357e2b3759d05/features/comments/commenting.feature#L148

https://github.com/activeadmin/activeadmin/blob/d01155f73a0e2cc27d712792270357e2b3759d05/spec/unit/comments_spec.rb#L86

https://github.com/activeadmin/activeadmin/blob/d01155f73a0e2cc27d712792270357e2b3759d05/lib/active_admin/orm/active_record/comments/comment.rb#L24

However this changes was made long time ago, so I'm not even sure that issue is still actual.

**Comment by deivid-rodriguez** [comment]
I think @krim is right, it's not good to have an `_id` column with a string type. I think the fact that those tests still pass mean this is no longer an issue in the versions of Rails currently supported. I would merge this.

**Comment by Fivell** [comment]
@deivid-rodriguez , the fact that those tests still pass also can mean they never worked as expected.

**Comment by Fivell** [comment]
@varyonic , @timoschilling , @deivid-rodriguez 
As I understood, root of that line was that active admin was going to support comments with foreign associations to objects with stringed primary keys, however there were not enough tests for this was added. 
If we're going to merge this, than we also should remove some pieces of code that are not needed anymore, for instance this method https://github.com/activeadmin/activeadmin/blob/d01155f73a0e2cc27d712792270357e2b3759d05/lib/active_admin/orm/active_record/comments/comment.rb#L23
and specs that are not needed anymore

**Comment by deivid-rodriguez** [comment]
Yep yep, basically revert https://github.com/activeadmin/activeadmin/pull/1063. The feature spec you link to could be wrong of course. It looks fine to me on at first glance though.

**Comment by Fivell** [comment]
@timoschilling , @varyonic, @seanlinsley  so support of this case is good idea what do you think https://github.com/activeadmin/activeadmin/issues/34 ?

**Comment by deivid-rodriguez** [comment]
@krim ping

**Comment by varyonic** [comment]
I think this is neither a bug-fix nor a feature.

**Comment by deivid-rodriguez** [comment]
You mean it won't make it to 1.0.0? Sounds good to me, just pinging the OP in case (s)he wants to get this done.

**Comment by krim** [comment]
I was make separated user access for manage active_admin comments. And when i was use cancancan and check objects ids for comparison with ids for access i really surprised when comparison work wrong for me. So, when i debugged this issue i found, that integer ids compared with string ids. Then i made this patch.

**Comment by deivid-rodriguez** [comment]
Hi @krim, thanks for getting back. I agree with this change. It would be nice to know when and where (AR, specific pg adapter?) the original problem was fixed, but it seems like too much archeology. The OP's logs in #34 show 1.9.2 and Rails 3.0, not sure anyone would like to go back there just to clarify this.

So I'd suggest that you rebase this PR and add a full revert of #1063, and you'll have my approval :wink:.

**Comment by krim** [comment]
I'm all done, but travis doesn't start tests with commit 967e397 and still use 28f867b for test. @deivid-rodriguez  please restart test

**Comment by deivid-rodriguez** [comment]
Isn't the check in the last commit the same as not checking anything? I mean, Rails 6 is not there yet, not even planned I think...

**Comment by krim** [comment]
I have typo in commit message, but not in commit :)

**Comment by deivid-rodriguez** [comment]
I don't understand, isn't `Rails::VERSION::MAJOR <= 5` true for every Rails version?

**Comment by krim** [comment]
My fault, fixed.
https://travis-ci.org/activeadmin/activeadmin/jobs/211880876 need to restart. Travis memory problem

**Comment by deivid-rodriguez** [comment]
@krim Yes, there was a problem with Travis, my fault. It should be fixed now. Could you try rebasing again? Now it should pass.

**Comment by Fivell** [comment]
@krim , @deivid-rodriguez , I would like to see this merged , but something wrong is here with rebasing

**Comment by deivid-rodriguez** [comment]
Well, the final diff seems good so squashing down to a single commit should work.

**Comment by krim** [comment]
Ready to merge?

**Comment by deivid-rodriguez** [comment]
Could you fix the commit history so the PR includes a single commit with the proposed change? If you can't fix this branch, feel free to create a new PR from a fresh branch off master and apply the change there.

**Comment by krim** [comment]
New PR here: #4868

**Pull request closed without merging**
