### PR TITLE
Cut 2.1.0

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
We have several interesting improvements in master. Let's release them!

### CODE REVIEW

**Comment by aruprakshit** [comment]
where I can see the changelog? Also why don't we have nested namespace support yet? :) I saw there is a PR, but never got merged.

**Comment by deivid-rodriguez** [comment]
The changelog the file named "CHANGELOG.md".

**Comment by aruprakshit** [comment]
@deivid-rodriguez I saw it. There is no new features I found. Thanks for your reply.

**Comment by deivid-rodriguez** [comment]
Let's do it!

**Comment by deivid-rodriguez** [comment]
Done!

**Pull request merged**
