### PR TITLE
Build pushes to all supported branches in CI

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
Previously we had "build only PRs" turned on on CircleCI config, but CircleCI makes an exception with the master branch, and still runs pushes to it.

In my mind, 1-4-stable (or whatever the last stable branch is) and master should have the same setup, meaning when we push to 1-4-stable, CI should be run. This is particularly interesting because right after release, it feels good that the exact state of the branch you are releasing from has been tested on CI.

Also (although this is only a side effect of these changes), this makes it possible again to run CI on a branch you have not opened a PR from (by adding the branch to the list of branches in the CircleCI config). Although @javierjulio has encouraged us to not do this, I think it's still interesting to support it, so we can fit the workflow of more developers.

Finally, this makes it explicitly in the CircleCI config which branches we support at a given time, which is also interesting.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
It sounds like this is not currently possible: once I add the configuration, PRs no longer build. The feature was requested [here](https://discuss.circleci.com/t/is-there-a-way-to-build-all-prs-to-specific-branches-and-those-branches-themselves/24851), but no response yet.

Closing.

**Comment by javierjulio** [comment]
@deivid-rodriguez perhaps it's worth commenting that we want to do this on ActiveAdmin and to give a reason why, basically share what we are trying to do here, that way it should hopefully clear up why its helpful/needed.

If we revisit this I won't have an issue with it by the way, I just feel there are some nice advantages to going PR only that you helped me realize and detail. If this helps keep CI consistent for master and stable branch releases though I'm fine with that. Thanks! 👍🏻

**Comment by deivid-rodriguez** [comment]
> @deivid-rodriguez perhaps it's worth commenting that we want to do this on ActiveAdmin and to give a reason why, basically share what we are trying to do here, that way it should hopefully clear up why its helpful/needed.

I tried to do this in the PR description, paragraphs 2 and 4 would be the reasons to do it. I'll try to explain it again. When we release from a non master branch, CI has not been run for the exact code that it's going to be released. The closest thing to it is the last PR to that branch, but it's not 100% the same thing. In any case, this is not supported by CircleCI, and when we implement #5518 it will be fixed anyways, so no big deal! :smiley:.

**Comment by deivid-rodriguez** [comment]
Exactly!

CircleCI by default does not build pushes to any branches, but makes an exception for master (see attached screenshot). I would like it to make exceptions for each supported branch, not only master. I tried to do that by toggling the UI option off, and making the changes proposed in this PR, but the result of it is that PR's are no longer built, only pushes to branches, that's why I closed this.

project settings activeadmin activeadmin circleci

**Comment by deivid-rodriguez** [comment]
Aaaaaah, you were indeed misunderstood, now I see what you meant! :+1:

**Comment by javierjulio** [comment]
@deivid-rodriguez haha no problem! I figured that was the case. I was wondering why was I getting a lengthy description and not CircleCI. 😂 Thanks! Sorry for the confusion.

**Pull request closed without merging**
