### PR TITLE
change exec context for batch_action form option

### PR DESCRIPTION
**Pull request by timoschilling**
fix for a https://github.com/activeadmin/activeadmin/pull/1815#issuecomment-59659670

### CODE REVIEW

**Comment by Fivell** [comment]
@timoschilling , please take a look at this implementation https://github.com/Fivell/activeadmin/commit/8d0ffc34cd592e0588ce566a6b99ff39d29dda37

**Comment by Fivell** [comment]
@timoschilling , any updates for this? Thanks

**Comment by timoschilling** [comment]
@Fivell maybe do you want to continue the work on this PR? If yes create a new branch forked form the `fix_batch_action_context` branch and create a new PR, I will close this one then

**Comment by Fivell** [comment]
@timoschilling , yes I want this to be merged. I don't know how to create new fork if I already has one. Can you help with this?

**Comment by timoschilling** [comment]
@Fivell sorry, I mean a branch which is based on `fix_batch_action_context` instead of `master`. Then you can continue the work on my base.

**Comment by timoschilling** [comment]
Closed by #3751

**Comment by Fivell** [comment]
@timoschilling , so will you merge it to master? #3751 was merged to your fix_batch_action_context branch

**Comment by timoschilling** [comment]
@Fivell my mistake, I have think your PR was merged into master. Tanks for the good work

**Pull request merged**
