### PR TITLE
Bump pry-byebug

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
I released a new `pry-byebug` version, but `dependabot` didn't create PRs in realtime for some reason.

This PR updates the dependency everywhere.

### CODE REVIEW

**Comment by javierjulio** [comment]
@deivid-rodriguez FWIW the Dependabot checks are showing errors. It could be it failed before it would have gotten the point where it would see an update for pry-byebug? I've run into this before so figure worth sharing. I tried bumping for now to see if it will help but likely will fail again. I'll share the log info, it was failing on formtastic.

**Comment by javierjulio** [comment]
Nevermind, that doesn't seem to be the cause but here is the formtastic error:

```
updater | INFO <job_27056152> Checking if formtastic f95dddae2fe57a9ecadd22a4b53b86eedee659d2 needs updating
updater | I, [2020-03-21T21:22:21.022337 #74]  INFO -- sentry: ** [Raven] Sending event 2bfb4308b37b46bda3d82e5f6d794f86 to Sentry
  proxy | 2020/03/21 21:22:41 POST https://sentry.io:443/api/1425239/store/
  proxy | 2020/03/21 21:22:41 200 https://sentry.io:443/api/1425239/store/
updater | ERROR <job_27056152> Error processing formtastic (RuntimeError)
updater | ERROR <job_27056152> Multiple sources! {:type=>"git", :url=>"git://github.com/justinfrench/formtastic.git", :branch=>"master", :ref=>"master"}, {:type=>"git", :url=>"https://github.com/justinfrench/formtastic.git", :branch=>"master", :ref=>"master"}
```

In regards to the pry-byebug, is it getting there but it's not able to do an update. Not sure if that has to do with our config or a lock conflict it can't resolve on its own.

```
updater | INFO <job_27056152> Checking if pry-byebug 3.8.0 needs updating
  proxy | 2020/03/21 21:23:02 GET https://rubygems.org:443/api/v1/versions/pry-byebug.json
  proxy | 2020/03/21 21:23:02 200 https://rubygems.org:443/api/v1/versions/pry-byebug.json
updater | INFO <job_27056152> Latest version is 3.9.0
  proxy | 2020/03/21 21:23:03 GET https://index.rubygems.org:443/versions
  proxy | 2020/03/21 21:23:03 206 https://index.rubygems.org:443/versions
  proxy | 2020/03/21 21:23:04 GET https://index.rubygems.org:443/info/treetop
  proxy | 2020/03/21 21:23:04 206 https://index.rubygems.org:443/info/treetop
updater | INFO <job_27056152> Requirements to unlock update_not_possible
updater | INFO <job_27056152> Requirements update strategy bump_versions_if_necessary
updater | INFO <job_27056152> No update possible for pry-byebug 3.8.0
```

**Comment by deivid-rodriguez** [comment]
Interesting, where do you see these logs? In dependabot's UI?

By the way this PR should be ready!

**Comment by javierjulio** [comment]
@deivid-rodriguez yes, go to https://app.dependabot.com/accounts/activeadmin and just click on the red alert icon for any of the 3 gemfile reports. Here are direct links to each log:
- 5.2 https://app.dependabot.com/accounts/activeadmin/update-logs/27056154
- 6.0TL https://app.dependabot.com/accounts/activeadmin/update-logs/27056153
- 6.0 https://app.dependabot.com/accounts/activeadmin/update-logs/27056152

**Comment by deivid-rodriguez** [comment]
Thanks @javierjulio. I had a look and actually managed to reproduce the issue locally. I reported to dependabot [here](https://github.com/dependabot/dependabot-core/issues/1753).

Regarding the `formatastic` issue, I guess we should report it too, but it should still happen on master after merging this PR, so we can do it later.

I'll merge this now, thanks!!

**Comment by javierjulio** [comment]
Awesome thanks!

**Pull request merged**
