### PR TITLE
Batch action form from partial

### PR DESCRIPTION
**Pull request by mmustala**
Hi,

I needed some more control over how the batch action form works and added a functionality for giving a partial name for the batch_action form.
```ruby
    batch_action :action_name, form: 'name_of_the_partial' do |ids, inputs|
      #do your stuff here
    end
```
The partial should contain the form with "form" tag although only the html in the form tag is extracted and put into the dialog. The submit button is removed if the form has one.

The partial could look for example like this
```erb
    <%= form_tag '#' do %>
      <div>
        <%= label_tag 'additional_info', 'Additional Info' %>
        <%= text_field_tag 'additional_info', nil, placeholder: 'Info' %>
      </div>
      <div>
        <%= label_tag 'do_action', 'Do Action' %>
        <%= check_box_tag 'do_action' %>
      </div>
      <p>Affects ids</p>
      <% ids.each do |id| %>
        <%= id %>
      <% end %>
    <% end %>

### CODE REVIEW

**Comment by mmustala** [comment]
@timoschilling do you think this could be merged some time? Anything you need me to add into it before merging? The Travis build seemed to fail on something other than my code. Is there a way to redo the build or will I need to send a dummy commit?

**Comment by mmustala** [comment]
@seanlinsley @timoschilling Any feedback would be much appreciated.

**Comment by mmustala** [comment]
I rebased this branch to the current master. @timoschilling @seanlinsley do you think this feature could be merged to Active Admin?

**Comment by chdem** [comment]
Hi,

I would love to add this to my current version of active admin !
How could I do that (not really familiar with this kind of things in git, sorry), as the merge request is still opened !

Thank you !

**Comment by mmustala** [comment]
I'm not sure if you would be able to refer to my activeadmin repo in your Gemfile. If that is not possible you can always fork the activeadmin repo and apply all the same changes. Then use your own repo in Gemfile.

**Comment by chdem** [comment]
@mmustala : First, i didn't congratulates you for the job ! Thank you for that !
Secondly, changing my Gemfil is a good idea ! 
Seems to be possible to add this in my gemfile :
`gem 'activeadmin' , git: 'https://github.com/activeadmin/activeadmin.git', ref: 'a723'`

Unfortunately, this is not running, because the commit is not available in the master ? :( 
```
$ bundle install
Fetching https://github.com/activeadmin/activeadmin.git
fatal: Needed a single revision
Git error: command `git rev-parse --verify a723` in directory /home/chdem/.rvm/gems/ruby-2.2.1@base_lib_gems/cache/bundler/git/activeadmin-65c0b1da5658f4f9f4661e7b7bbf5cb4ecdfde1d has failed.
Ref 'a723' was not found. Perhaps you mispelled it?
If this error persists you could try removing the cache directory '/home/chdem/.rvm/gems/ruby-2.2.1@base_lib_gems/cache/bundler/git/activeadmin-65c0b1da5658f4f9f4661e7b7bbf5cb4ecdfde1d'
```

@timoschilling @seanlinsley : Please, is it possible to do a merge ?
This is a great enhancement as we could create better forms and let them be shown on the same page as the first action (with the popup). This is really good for user experiment !

**Comment by chdem** [comment]
Hi,

I'm encountering an error when I try to open a batch_action form after using scopes or tab paginations : the popup contains the index page, not the form : 

batch_action_popup_nok


If I delete the URL parameters to go back to the original URL, reload the page and try to open batch_action form, everything's going well !


Looking at the console, I have this in normal case : 
`Started GET "/admin/demandes/batch_action_form_view?partial_name=add_new_lib
Processing by Admin::DemandesController#batch_action_form_view as */*
Parameters: {"partial_name"=>"add_new_lib"}
Rendered admin/demandes/_add_new_lib.html.haml (20.2ms)
Completed 200 OK in 25ms (Views: 24.5ms | ActiveRecord: 0.0ms)`

And in the 'popup with index page' case I have this : 
`Started GET "/admin/demandes?order=id_desc&page=2/batch_action_form_view?partial_name=add_new_lib"
Processing by Admin::DemandesController#index as */*
Rendered admin/demandes/_demandes_tmp.html.haml (0.1ms)
Rendered /home/chdem/.rvm/gems/ruby-2.2.1@base_lib_gems/bundler/gems/activeadmin-6c1335df71f2/app/views/active_admin/resource/index.html.arb
Completed 200 OK in 204ms (Views: 195.4ms | ActiveRecord: 7.2ms)`

As you can see, the URL is composed of 2 differents parts in the second case : 
/admin/demandes?order=id_desc&page=2/batch_action_form_view?partial_name=add_new_lib

I think we have to ignore the index parameters but I don't know how to do that.

Any ideas ?

Thank you !

**Comment by timoschilling** [comment]
I think this solution is oversized, the idea is good, but the code should be much smaller for a problem like this.

**Comment by vfonic** [comment]
Hey @timoschilling do you know if this functionality was ever integrated in activeadmin? I had a quick glance at the code and I think it's quite interesting approach: fetch the form directly from the backend so we can render any form (partial) for batch action that we can also use as a full page edit form or part of it.

Is there any other recommended way or some other gem that offers this functionality?

What I need is to be able to offer multi-choice selection (many to many). In formtastic that's super simple with `as: :checkboxes`.

Thanks!

**Pull request closed without merging**
