### PR TITLE
Test against Rails 7.2

### LINKED ISSUE #8367: Rails 7.2: prepare CI for testing
### Upstream blockers:
- [x] Ransack activerecord-hackery/ransack#1491
- [x] Database Cleaner (pending release) DatabaseCleaner/database_cleaner-active_record#102
- [x] DatabaseCleaner/database_cleaner-active_record#106

### TODO:
- [x] #8368
- [x] ~Triage cucumber failures https://github.com/activeadmin/activeadmin/actions/runs/9438091597/job/25994708535?pr=8371~ They depend by database cleaner. Fixed on database cleaner main

### PR DESCRIPTION
**Pull request by tagliala**
Rebase after:
- [x] #8370
- [x] #8369
- [x] #8372

Close #8367

### CODE REVIEW

**Comment by tagliala** [comment]
All specs pass and I do not see warnings

**Comment by javierjulio** [comment]
@tagliala changes look great, thank you. Did you want to have this reviewed and merged as is or prefer to wait for final release?

**Comment by tagliala** [comment]
> Did you want to have this reviewed and merged as is or prefer to wait for final release?

Maybe it is better to wait for the final release or an rc at least

**Comment by tagliala** [comment]
Tested against RC1

**Review by javierjulio — APPROVED** [review]
Thanks!

**Pull request merged**
