### PR TITLE
Add Chinese translations of unsupported broswer

### PR DESCRIPTION
**Pull request by zhaqiang**

### CODE REVIEW

**Comment by varyonic** [comment]
@doabit @jiandanxinli do you still use AA?

**Comment by deivid-rodriguez** [comment]
I'm :+1: for this, let's trust the community! :heart:

**Comment by doabit** [comment]
@vairix-ssierra Yes, these translation no problem.

**Comment by deivid-rodriguez** [comment]
Thank you very much @doabit & @zhaqiang. Would you mind if we pinged you when we get more chinese contributions? Our current knowledge of chinese is... missing. :)

**Comment by doabit** [comment]
@deivid-rodriguez Yes, glad to help.

**Comment by zhaqiang** [comment]
@deivid-rodriguez Of course not.

**Pull request merged**
