### PR TITLE
update brazilian locale

### LINKED ISSUE #3866: missing locales
I've used master branch version and I started to see missing locales:

<pre>
remote: git://github.com/activeadmin/activeadmin.git
  revision: 53e85d6a2cf4f5bc083e8da7c6786b5cd69ce7a1
  specs:
    activeadmin (1.0.0.pre1)
      arbre (~> 1.0, >= 1.0.2)
      bourbon
      coffee-rails
      formtastic (~> 3.1)
      formtastic_i18n
      inherited_resources (~> 1.6)
      jquery-rails
      jquery-ui-rails (~> 5.0)
      kaminari (~> 0.15)
      rails (>= 3.2, < 5.0)
      ransack (~> 1.3)
      sass-rails
    formtastic (3.1.3)
    formtastic_i18n (0.2.0)
</pre>

missing

That is not reflected in locales:
https://github.com/activeadmin/activeadmin/blob/master/config/locales/en.yml#L27
https://github.com/activeadmin/activeadmin/blob/master/config/locales/pt-BR.yml#L27

I can send a pull request but I need to know if it was a intentional change or not.

### PR DESCRIPTION
**Pull request by kivanio**
fix #3866

### CODE REVIEW

**Comment by timoschilling** [comment]
Why do you add `filters.predicates.eq`? ActiveAdmin use only `equals`.

**Comment by kivanio** [comment]
@timoschilling see my last comment in #3866

**Comment by timoschilling** [comment]
You don't talk about `eq` in your comment and you don't have `gteq`/`lteq` in this commit but you talk about that in the comment. If you remove `eq` I can merge this commit, a locale can't have a key that don't exist in the en locale. Every thing else need's to discussion in #3866.

**Comment by kivanio** [comment]
@timoschilling `eq` is removed

**Pull request merged**
