### PR TITLE
Get ready for 2.10.0 release

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
Regardless of any more ambitious plans for future versions, or Rails 7 support, we should get a version out. It's been too long.

### CODE REVIEW

**Comment by Fs00** [comment]
@deivid-rodriguez Can also #6954 be included in this release? Or is it too late?

**Review by timoschilling — APPROVED** [review]

**Review by javierjulio — APPROVED** [review]

**Comment by deivid-rodriguez** [comment]
@javierjulio @timoschilling Ok with also shipping #6954 with this or you prefer to go ahead with what's now in the main branch?

**Comment by timoschilling** [comment]
From my point of view we can merge that PR and release then.

**Comment by deivid-rodriguez** [comment]
2.10.0 is out, hopefully it's all good!

**Pull request merged**
