### PR TITLE
WIP: Test for rubinius with travis

### PR DESCRIPTION
**Pull request by dmitry**

### CODE REVIEW

**Comment by timoschilling** [comment]
Sorry but I will not merge failing travis setup changes.

We can add rbx to the `allow_failures` list, or you fix active admin for rbx.

**Comment by dmitry** [comment]
Yes, I'm just started to work on rbx. Using travis for testing is easier, than testing locally. Sorry if it's a bad workflow here, but I'm using this often at my work. So basically this is WIP PR.

**Comment by timoschilling** [comment]
Ok, but why you don't use a branch on your fork, you only need to activate travis on travis.org for your fork repo.

**Comment by dmitry** [comment]
Who knows, maybe someone will help me, maybe someone will find out this feature helpful and can give additional advices. Think about it like a WIP proposal :)

**Comment by timoschilling** [comment]
Ok, your are welcome!

**Comment by kennethkalmer** [comment]
@dmitry I'm going to attempt the JRuby branch, we can compare notes as we go along.

**Comment by dmitry** [comment]
@kennethkalmer :+1:

**Comment by kennethkalmer** [comment]
It is happening in #3742

**Comment by seanlinsley** [comment]
This isn't being worked on, so I'm going to move it to a ticket instead of a PR.

**Pull request closed without merging**
