### PR TITLE
Full switch to circle ci

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
The missing images were added to the custom circleci images. Let's see how they behave.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
I also changed the status badge in the README to point to CircleCI, although if we ever implement #5518, we'll no longer need a status badge :smiley:.

**Comment by deivid-rodriguez** [comment]
Close! Jruby 9.2 is passing, but 9.1 is not because circleci images are not available. That's because official images are not available for 9.1, and circleci builds their images on top of the official ones. I opened a ticket  about this: https://github.com/cpuguy83/docker-jruby/issues/35.

**Comment by javierjulio** [comment]
Wouldn’t be best to just support the latest version? Do we really need 9.1 as well? Either way it’s great this got added. I was about to ask you about making our own images instead but didn’t expect it to be done so quickly. Thanks!

**Comment by deivid-rodriguez** [comment]
@javierjulio I added it because given that we test against all the supported major MRI's (2.3, 2.4 and 2.5), the correct thing felt to also test against all supported major jrubies (9.1, 9.2). Basically, test against every supported supported version that can be expected to have different features and behavior.

The upstream issue has already been closed and 9.1 has been added to the official manifests, so the circleci images should be available soon!

**Comment by javierjulio** [comment]
Makes sense. I’m glad then it’s also being added. We’ll have it all running on CircleCI soon. Thanks again!

**Comment by deivid-rodriguez** [comment]
All issues are fixed, so this is passing now!

Still, they said "we'll merge it into master shortly", so I'll wait a bit for the images to be made official so I can update this PR and merge it with the updated references, so we don't need a followup PR for that.

**Comment by javierjulio** [comment]
@deivid-rodriguez ok I was following the conversation in the circleci-images repo. Sounds good. 👍🏻 Please ping me when this is ready! Be good to get this in along with #5530. ❤️

**Comment by javierjulio** [comment]
@deivid-rodriguez I'm not sure what's best. If you change your mind and rather merge now, just give me a heads up. I'll approve and merge it in.

**Comment by deivid-rodriguez** [comment]
Let's go crazy and merge it! :smiley:

**Comment by javierjulio** [comment]
Buckle up, @deivid-rodriguez. 😏

**Pull request merged**
