### PR TITLE
ADD: Action item labels per model

### PR DESCRIPTION
**Pull request by grzegorzblaszczyk**
…tests (+1 squashed commit)

Squashed commits:
[f60e73a] ADD: Action item labels per model - handling 'translation missing'
[7c6f15a] ADD: Action item labels per model - handling 'translation missing'
[5a37358] ADD: Action item labels per model

### CODE REVIEW

**Comment by varyonic** [comment]
See also #2823

**Comment by Fivell** [comment]
@varyonic , should we close this?

**Comment by deivid-rodriguez** [comment]
I think we can definitely close this.

**Comment by grzegorzblaszczyk** [comment]
@deivid-rodriguez @varyonic @Fivell Yes, we should close this. 😄

**Pull request closed without merging**
