### PR TITLE
Get ready for 2.8.0 release

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
While tagging PRs for this release, I wonder if:

* We should group i18n improvements under a `type: documentation` tag, and allow patch releases to include this kind of changes.
* We should group documentation improvements under a `type: documentation` tag, and allow patch releases to include this kind of changes too.

It's a bit fuzzy whether to tag these changes of bug fixes or enhancements, so making separate groups makes things easier I believe.

Also, these improvements are more minor than real features like "PORO decorators" in this case, so moving them to separate sections makes features stand out more.

### CODE REVIEW

**Comment by javierjulio** [comment]
@deivid-rodriguez I think that's a great idea! Documentation is a big part of this project so it helps to surface that in the changelog when it has been improved. I've seen other projects specifically identify documentation updates in their changelog so it doesn't hurt. Can we just create the PR label or would we have to update the rake tasks as well? In the meantime, I'll approve this and merge.

**Comment by deivid-rodriguez** [comment]
We'd need to update the rake task so that the `Documentation` and `I18n` sections are generated in the changelog. NOTE: I edited my original message because it had the typo of mentioning `type: documentation` twice when I meant `type: i18n` in the first bullet point.

If this sounds good to you, I'll create a PR and run an update pass on the changelog.

**Comment by javierjulio** [comment]
@deivid-rodriguez yes sounds great, let's do it! Thanks.

**Comment by deivid-rodriguez** [comment]
Activeadmin 2.8.0 is out at [npmjs.com](https://www.npmjs.com/package/@activeadmin/activeadmin/v/2.8.0) and [rubygems.org](https://rubygems.org/gems/activeadmin/versions/2.8.0).

**Comment by Fivell** [comment]
@deivid-rodriguez congrats! hope 2.8.1 with PR 6422 and 6363 is not so far away

**Comment by deivid-rodriguez** [comment]
Yes, I'll review those next and ship them as a patch level release :+1:.

**Pull request merged**
