### PR TITLE
Fix `has_many` syntax in forms documentation

### PR DESCRIPTION
**Pull request by krzcho**
has_many needs plural

### CODE REVIEW

**Review by javierjulio — APPROVED** [review]

**Review by deivid-rodriguez — APPROVED** [review]
Thanks!

**Comment by krzcho** [comment]
Actually I am now not sure if it was a typo or not :D
For sure I needed plural (as my model had many) but the description above claims "You can create forms with nested models using the has_many method, even if your model uses has_one:" - so this code could have been an example of that (however not the best one as normally post has many comments)

**Comment by deivid-rodriguez** [comment]
Oh wow, nice catch. That's a weird detail of the API... Should we add an example of the `has_one` usage too?

**Comment by krzcho** [comment]
Nah :)

**Pull request merged**
