### PR TITLE
Drop rails 5.2 support

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
It's hard for us to support a big range of Rails versions, and Rails 5.2 is essentially not maintained anymore except for severe security issues. So I propose that we move on.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
This one should be ready. Codeclimate coverage checks didn't run not sure why, and branch settings need to be edited to reflect the new required checks.

**Comment by deivid-rodriguez** [comment]
Alright, as soon as I changed the required checks, the code coverage checks went through 👍.

**Review by Fivell — APPROVED** [review]
👍

**Comment by deivid-rodriguez** [comment]
Thanks!

**Pull request merged**
