### PR TITLE
Release 2.7.0

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
Time to cut master and release ActiveAdmin 2.7.0, with optional support for webpacker assets, and the nested submenus feature.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
Sorry for the delay here. @javierjulio you're good with the release? Anything you'd like to get in?

**Comment by javierjulio** [comment]
@deivid-rodriguez no problem. Sorry, I didn't realize it was ready! Just set me for review next time and I'll get a notification to check it. It's no bother at all! ❤️ I don't have anything else. I think its ready to go, thanks!

**Comment by deivid-rodriguez** [comment]
No problem, not in a hurry! :) Let's do this!

**Comment by javierjulio** [comment]
Big shout out to @taralbass, @sgara, @Looooong, @irmela and @giapnhdev! Thank you again for your contributions in this release. ❤️

**Comment by deivid-rodriguez** [comment]
2.7.0 is out!

**Pull request merged**
