### PR TITLE
Search Status Sidebar

### PR DESCRIPTION
**Pull request by ccallebs**
In response to #2122. 

I have one broken feature spec in `features/symbol_leak.feature:20` -- not quite sure how to fix it.

### CODE REVIEW

**Comment by ccallebs** [comment]
@timoschilling Just checking in again on this. I don't mean to bug you, just making sure it's on your radar.

**Comment by timoschilling** [comment]
Don't worry, it's on my radar :wink:

**Comment by debreczeni** [comment]
:+1: for merging this in :)

**Comment by timoschilling** [comment]
@ccallebs I have extend this I18n support for this PR in e82b68ca90e8a25f34805e9983d7353c2c33c05c. By doing that I found that your PR has no specs / features for the View. Maybe do you want to add some?

**Comment by ccallebs** [comment]
@timoschilling Sure thing, just saw the comment you made on my other branch as well. There are a few specs on this branch, but I'll add more complete coverage.

I'll try to get to those this weekend and get back to you.

**Pull request merged**
