### PR TITLE
split application.js into septerate initializers

### PR DESCRIPTION
**Pull request by timoschilling**
Each part of the `application.js.coffee` has moved into a own file. Now we have structured code, wich one file for one feature `app/assets/javascripts/active_admin/initializers/FEATURE.js.coffee`.
I think is a much more cleaner code.
refs #3588

### CODE REVIEW

**Comment by seanlinsley** [comment]
@timoschilling this change makes sense, but there's a merge conflict now.

**Comment by timoschilling** [comment]
I will try to find some time

**Comment by seanlinsley** [comment]
Think you can find some time to update this PR?

**Comment by timoschilling** [comment]
yes

**Pull request closed without merging**
