### PR TITLE
add pt-BR missing translations 1-1-stable

### PR DESCRIPTION
**Pull request by renatocn**

### CODE REVIEW

**Comment by varyonic** [comment]
Looks like PRs against 1-1-stable not being picked up by Travis.

**Comment by javierjulio** [comment]
Our travis config specifies only the master branch. Either we remove it or specify stable-1-1. I checked the Rails repo to see what they specify but they don't even specify branches so they go with the travis default which my guess would be on all branches.

**Comment by deivid-rodriguez** [comment]
The I'd say let's add the branch to `travis.yml`. It'll also give a quick hint of the currently supported branches, which seems nice.

**Comment by varyonic** [comment]
While David has a valid point my vote is to follow Rails.

**Comment by deivid-rodriguez** [comment]
Ok, so let's go back to our previous setting and test all branches by default. @renatocn Could you remove the whole `branches:` entry from our `.travis.yml` so that this gets tested?

**Comment by renatocn** [comment]
@deivid-rodriguez sure. Done.

**Comment by deivid-rodriguez** [comment]
Failing against `jruby` as expected, since the PR is not rebased on top of #5112. Merging, thanks @renatocn!

**Pull request merged**
