### PR TITLE
An extra small tip for sidebar feature

### PR DESCRIPTION
**Pull request by lboix**

### CODE REVIEW

**Comment by timoschilling** [comment]
Nice, but can you change the wording and move it up before "You can also render a partial"

You can access your model as resource in the sidebar too:

```ruby
sidebar :custom, only: :show do
  resource.a_method
end
```

**Comment by lboix** [comment]
Thanks for your feedback, it's done!

**Comment by timoschilling** [comment]
Can you put it into one commit?
```bash
git reset HEAD~2
git add --all
git commit -m "An extra small tip for sidebar feature"
```

**Comment by lboix** [comment]
Done, but not sure that it worked properly...

Do you want me to delete this merge request and create a new one ?

**Comment by timoschilling** [comment]
That not necessary I simply picked this commit 223c083aaee86915d4883ed990f251278535dbcc

**Pull request closed without merging**
