### PR TITLE
add protocol to permitted_params for ssl users

### PR DESCRIPTION
**Pull request by randito78**

### CODE REVIEW

**Comment by timoschilling** [comment]
Your `:protocol` key is application specific and should not be part of active admin

**Comment by seanlinsley** [comment]
@timoschilling not necessarily. If `:protocol` is a parameter that Rails itself defines, it makes sense to always permit it.

**Comment by timoschilling** [comment]
I don't think that rails adds something like `:protocol` to the `params`.

**Comment by seanlinsley** [comment]
I can't find any documentation for this. And if this were to be merged, ideally it should have a test to go along with it. Closing for now.

**Pull request closed without merging**
