### PR TITLE
Relax Rails dependency for Rails 5.2.0

### PR DESCRIPTION
**Pull request by junk0612**
Rails 5.2.0 has been released!

- http://weblog.rubyonrails.org/2018/4/9/Rails-5-2-0-final/

### CODE REVIEW

**Comment by zorab47** [comment]
The error in CI looks to be related to capybara:

```
Exception: ArgumentError: wrong number of arguments (given 2, expected 0)
--
0: /home/charles/.gem/ruby/2.3.5/gems/cucumber-rails-1.4.0/lib/cucumber/rails/capybara/javascript_emulation.rb:12:in `click_with_javascript_emulation'
1: /home/charles/.gem/ruby/2.3.5/gems/capybara-3.0.1/lib/capybara/node/element.rb:133:in `block in click'
2: /home/charles/.gem/ruby/2.3.5/gems/capybara-3.0.1/lib/capybara/node/base.rb:83:in `synchronize'
3: /home/charles/.gem/ruby/2.3.5/gems/capybara-3.0.1/lib/capybara/node/element.rb:133:in `click'
4: (pry):7:in `block in <top (required)>'
```

**Comment by deivid-rodriguez** [comment]
> Same issue as last year (#4916). I'm convinced it should be <= 5.2.x so we remember to update it to <= 6.0.x next year and it doesn't break again when Rails exits 6.0 beta.

@varyonic You might be interested in [this](https://github.com/rubygems/rubygems/pull/2266) `rubygems` thread. Now that I've been bitten by it, I agree with you :)

**Comment by zorab47** [comment]
@junk0612 would you rebase and adjust the version constraint to be `<= 6.0`?

**Comment by zorab47** [comment]
Closing in favor of #5399. Thank you for the PR!

**Pull request closed without merging**
