### PR TITLE
update old hash syntax, fixed typos

### PR DESCRIPTION
**Pull request by Fivell**
refs #2968

### CODE REVIEW

**Comment by varyonic** [comment]
Why this one?  See also  `rubocop --only Style/HashSyntax`?  Works with `--auto-correct`  Hound is installed but disabled? #4104.

**Comment by Fivell** [comment]
@varyonic , you wan't me update all the old hash syntax?

**Comment by deivid-rodriguez** [comment]
I'm in favor of selectively globally autocorrecting certain offenses. But be aware, this can be problematic when rebasing already opened PR's, specially when they are big and/or the user doesn't know a lot of git. We might want to reduce this list of opened PR's before applying this kind of changes.

**Comment by Fivell** [comment]
@deivid-rodriguez , ok I will make changes by hash syntax globally,  in any time I will  be able to squash and rebase when other PR's are merged.

**Pull request merged**
