### PR TITLE
Use ruby 2.7.2 in CI

### PR DESCRIPTION
**Pull request by deivid-rodriguez**

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
No idea what happened there. I restarted the CI.

**Comment by javierjulio** [comment]
I noticed another failure with ruby26rails60webpacker so I re-ran it in case its another fluke but maybe not. Let's see.

**Comment by deivid-rodriguez** [comment]
It seems to be consistently failing, although it passes for me locally... mmm. I'll look closer.

**Comment by deivid-rodriguez** [comment]
Hopefully CI goes green now and we can merge this :crossed_fingers:.

**Comment by deivid-rodriguez** [comment]
Definitely 2.7.2 specific, weird.

**Comment by deivid-rodriguez** [comment]
It seems fine with Github Actions :man_shrugging:. Since nobody has reported any issues on 2.7.2, let's ignore it.

**Pull request merged**
