### PR TITLE
(Backport) Fix attributes passed to form has_many not being set on new record form items

### PR DESCRIPTION
**Pull request by Fs00**
Backports #8550 for ActiveAdmin 3.x.

The diff is basically the same except for CSS classes that differ between AA 3 and 4.

### CODE REVIEW

**Review by javierjulio — APPROVED** [review]
Thanks!

**Comment by Fs00** [comment]
Would it be possible to get a new 3.x patch release with this change once #8650 is merged? This change would really be useful to us.
It's already available in 4.0 beta releases since a while, but unfortunately we won't be able to upgrade in the near future.

**Comment by mgrunberg** [comment]
> Would it be possible to get a new 3.x patch release with this change once #8650 is merged? This change would really be useful to us. It's already available in 4.0 beta releases since a while, but unfortunately we won't be able to upgrade in the near future.

@Fs00 A new v3 version is gonna be released in the following days. The plan is to merge that PR and another one, then cut a new release.

**Comment by Fs00** [comment]
This is great news, thank you!

**Pull request merged**
