### PR TITLE
fix for activeadmin undefined mixin 'global-reset'

### PR DESCRIPTION
**Pull request by mukeshsingh**
This is for undefined mixin error while precompile for production.

### CODE REVIEW

**Comment by timoschilling** [comment]
I think there is a bug somewhere in your application.

Please open a issue for that, this is not the solution.

**Comment by seanlinsley** [comment]
It would be useful to know what version of Rails and Sprockets you're using.

**Comment by mukeshsingh** [comment]
Hi ActiveAdmin,

I am using below versions:

* rails (4.0.4)
* sprockets (2.12.4)
* sprockets-rails (2.0.1)

gem list from bundle
* actionmailer (4.0.4)
  * actionpack (4.0.4)
  * activeadmin (1.0.0.pre2)
  * activemodel (4.0.4)
  * activerecord (4.0.4)
  * activerecord-deprecated_finders (1.0.4)
  * activesupport (4.0.4)
  * arbre (1.0.3)
  * arel (4.0.2)
  * bcrypt (3.1.10)
  * bourbon (3.2.4)
  * builder (3.1.4)
  * bundler (1.10.6)
  * coffee-rails (4.1.1)
  * coffee-script (2.4.1)
  * coffee-script-source (1.8.0)
  * devise (3.5.3)
  * erubis (2.7.0)
  * execjs (2.5.2)
  * faraday (0.9.2)
  * formtastic (3.1.3)
  * formtastic_i18n (0.5.0)
  * has_scope (0.6.0)
  * hashie (3.4.3)
  * hike (1.2.3)
  * i18n (0.7.0)
  * inherited_resources (1.6.0)
  * jbuilder (1.5.3)
  * jquery-rails (3.1.4)
  * jquery-ui-rails (5.0.5)
  * json (1.8.3)
  * jwt (1.5.2)
  * kaminari (0.16.3)
  * libv8 (3.16.14.13)
  * mail (2.5.4)
  * mime-types (1.25.1)
  * minitest (4.7.5)
  * multi_json (1.11.2)
  * multi_xml (0.5.5)
  * multipart-post (2.0.0)
  * mysql2 (0.3.18)
  * oauth (0.4.7)
  * oauth2 (1.0.0)
  * omniauth (1.3.1)
  * omniauth-facebook (3.0.0)
  * omniauth-google (1.0.2)
  * omniauth-oauth (1.1.0)
  * omniauth-oauth2 (1.4.0)
  * orm_adapter (0.5.0)
  * polyamorous (1.3.0)
  * polyglot (0.3.5)
  * rack (1.5.5)
  * rack-test (0.6.3)
  * rails (4.0.4)
  * railties (4.0.4)
  * rake (10.5.0)
  * ransack (1.7.0)
  * rdoc (4.2.1)
  * ref (2.0.0)
  * responders (1.1.2)
  * sass (3.2.19)
  * sass-rails (4.0.5)
  * sdoc (0.4.1)
  * sprockets (2.12.4)
  * sprockets-rails (2.0.1)
  * therubyracer (0.12.2)
  * thor (0.19.1)
  * thread_safe (0.3.5)
  * tilt (1.4.1)
  * treetop (1.4.15)
  * turbolinks (2.5.3)
  * tzinfo (0.3.46)
  * uglifier (2.7.2)
  * warden (1.2.4)
  * will_paginate (3.0.7)


Thanks,
Mukesh

**Comment by timoschilling** [comment]
Please open a issue for that!

**Comment by mukeshsingh** [comment]
As per your suggestion I opened a issue for that.
https://github.com/activeadmin/activeadmin/issues/4322 <https://github.com/activeadmin/activeadmin/issues/4322>

**Pull request closed without merging**
