### PR TITLE
inline deletion of comments

### PR DESCRIPTION
**Pull request by timoschilling**
this is a part implementation of @seanlinsley's https://github.com/activeadmin/activeadmin/issues/1903#issuecomment-13637169
delete comment

### CODE REVIEW

**Comment by ernsheong** [comment]
+1 Status on this?

**Comment by sprite2005** [comment]
Will this be merged soon?

**Comment by timoschilling** [comment]
It needs a rebase and some test. Maybe some else will work on that. If yes, create a merge request based on the [1903_inline_delete_comments](https://github.com/activeadmin/activeadmin/tree/1903_inline_delete_comments) branch and against the 1903_inline_delete_comments branch.

**Comment by seanlinsley** [comment]
I think this should have a feature flag. Some developers might not want comments to be deletable, for the sake of keeping an audit log

**Comment by timoschilling** [comment]
@seanlinsley :+1:

**Comment by seraphimlord** [comment]
Hello, just want to ask. Why isn't this merge into the master yet? Is there still more issues with it?

**Comment by izumeroot** [comment]
Hello everyone. When will it added to master?

**Comment by a0n** [comment]
I would love to see this in master too.

**Comment by jostster** [comment]
@timoschilling does this allow scoping of comments so only people who created the comments can edit them and only super admins can edit all and delete all?

**Comment by timoschilling** [comment]
@jostster you can control that via the authorization (cancan for example)

**Comment by timoschilling** [comment]
@andrewdang17 it's only supported by `>= 1.0.0.pre2`

**Pull request merged**
