### PR TITLE
Cancel buttons are now unstyled

### PR DESCRIPTION
**Pull request by knu**
Styles for cancel buttons are mistakenly removed in 6ebb4a7d, which this PR fixes.

### CODE REVIEW

**Comment by timoschilling** [comment]
Thanks :+1:

**Comment by knu** [comment]
That was quick, thanks!

Looking at the buttons closely, there seem to be some minor style differences between submit buttons and cancel buttons (namely border-radius and height), so I'd appreciate if you could fix them as appropriate.

**Comment by timoschilling** [comment]
In #3862 @javierjulio is doing a big overhaul of the css, maybe he can include that in his changes.

**Comment by knu** [comment]
OK, I'm in no particular hurry and will be looking forward to it.

**Comment by javierjulio** [comment]
@timoschilling yes its still in place in my repo. The problem was that "remove Iconic" branch removed this bit of CSS, my guess is you did a replace all on anything icon related and since the light-button and icon-size were on the same line it wiped both.

I plan to update it so we have a reusable button class rather than target each set of buttons individually. This way it'll be easier for when people customize ActiveAdmin they can just reuse a simple CSS class rather than having to write selectors and using our internal mixins. Nothing wrong with that bit on mixins but I think a button is such an essential part we can make it easier to access and use.

@knu thanks for finding and fixing this!

**Pull request merged**
