### PR TITLE
Lint docs

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
I added documentation linting through https://github.com/markdownlint/markdownlint. @varyonic, you had some kind of "staging site" where you could test this, right? In particular I'm worried about some relative links in the main page, which I'm not sure they'll work...

### CODE REVIEW

**Comment by varyonic** [comment]
I'm not maintaining a staging documentation site any more.  Linting seems like overkill to me, but go ahead if you want to.

**Comment by deivid-rodriguez** [comment]
Oh, ok. I'm actually not that worried about the links since relative files seem to work ok in other places of the docs. I think it's fine. But I'll double check if this is merged.

Also, the commit is not very atomic since I fixed all issues at once but note that the linter detected some real issues like unclosed quoting or unapplied headings. So I think it's useful.

**Comment by deivid-rodriguez** [comment]
I splitted the PR into separate commits to better motivate the changes.

**Comment by deivid-rodriguez** [comment]
@varyonic is a "meh" here, can anybody else give me the :+1: I need? :stuck_out_tongue_closed_eyes:

**Comment by deivid-rodriguez** [comment]
I'll sell it a bit more... Changes here help readability on small screens, fix some markdown errors and help editor syntax highlighters do their job better.

**Comment by javierjulio** [comment]
I love Markdown so I'm all for it! If it doesn't prove helpful we can always just remove it. Great job! 👍🏻

**Pull request merged**
