### PR TITLE
Workaround slow JRuby build

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
0d564c7 seems to workaround the slow jruby builds for me.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
Around 1h less that the our average build time!

**Comment by deivid-rodriguez** [comment]
Nope, there's none (at least when I checked). We would have to further isolate this and open one.

**Comment by deivid-rodriguez** [comment]
That's it! Setting `JAVA_OPTS="-Djava.security.egd=file:/dev/./urandom"` did the tricky! Kudos to @varyonic who got me on the right track!

**Comment by javierjulio** [comment]
@deivid-rodriguez I'm not familiar with jruby but @Fivell has already approved. Lets see what happens. I'm confident this will do it. You've worked hard on resolving this so thanks!

**Comment by deivid-rodriguez** [comment]
@Fivell approved an old version of this PR, but he approved based on build times, and they're still fast, and with a simpler patch. So it should still be fine! :)

**Comment by deivid-rodriguez** [comment]
Jruby is having the same problems in jruby/jruby#4696, so I'm no longer sure this was it... Let's wait and see.

**Comment by headius** [comment]
FWIW, the latest jruby-launcher gem (a native executable you can install) and the upcoming JRuby 9.1.15.0 bash script equivalent both have the urandom tweak shown here as a standard startup flag. Installing jruby-launcher in any *nix environment should be sufficient to get the tweaked property.

**Comment by headius** [comment]
See jruby/jruby#4696 and jruby/jruby#4857.

**Comment by deivid-rodriguez** [comment]
Thanks @headius. We're still adding `-J-Djava.security.egd=file:/dev/./urandom`, but I'll make sure we remove it once `9.1.15.0` is released!

By the way, we added the latest `activerecord-jdbc-releases` to our build [recently](https://github.com/activeadmin/activeadmin/pull/5248), and the full jruby matrix is passing `activeadmin`'s tests now!

**Pull request merged**
