### PR TITLE
Drop support for Rails 6.1

### PR DESCRIPTION
**Pull request by mgrunberg**
According to [Rails Maintenance Policy](https://guides.rubyonrails.org/maintenance_policy.html), Rails 6.1 is about to loose security update in a month more or less and reach EOL (check [here](https://endoflife.date/rails)).

We can keep support for Rails 6.1 as long as we want.

The PR is to track the required changes to drop support

### CODE REVIEW

**Comment by mgrunberg** [comment]
@javierjulio, @tagliala is it too premature to do this now? Considering we are working on a major release.

**Comment by javierjulio** [comment]
@mgrunberg no, I don't think so. We can leave this open until we are ready to merge. The [Rails maintenance page states that 6.1 is supported through October 1, 2024](https://rubyonrails.org/maintenance#security) for security releases only.

**Comment by tagliala** [comment]
Maybe this is a good time to ,erge

Since there are required workflows to pass

image

We can either remove those or bypass the rule for this PR

**Comment by javierjulio** [comment]
When we approve this, we'll remove those required status checks first before merging since they won't apply anymore. Since we are coming up on the date next week, I think it's fine to get ready to merge whenever. Thank you.

**Review by tagliala — COMMENTED** [review]
Should we add 

```yml
  TargetRailsVersion: 7.0
```

below

https://github.com/activeadmin/activeadmin/blob/3b54bde14bbce666198c73f1aac1e43458bdcc83/.rubocop.yml#L16

?

**Comment by javierjulio** [comment]
@tagliala I didn't realize that was an option in rubocop-rails but makes sense and it is supported as I see mentions in the docs, thank you. Feel free to add it here if you like Matias.

**Comment by mgrunberg** [comment]
I added the TargetRubyVersion. Thank @tagliala for the suggestion.

@javierjulio are we good to merge the PR now?

**Review by tagliala — APPROVED** [review]
I would merge this before dropping 3.0 support #8489

I'm going to disable the requirements for 6.1 actions. Done

**Review by javierjulio — APPROVED** [review]
Thanks!

**Pull request merged**
