### PR TITLE
Prepare 4.0.0.beta12 release

### PR DESCRIPTION
**Pull request by tagliala**

### CODE REVIEW

**Comment by tagliala** [comment]
I did this manually, is there a script?

**Comment by javierjulio** [comment]
@tagliala yes, there is a `bin/prep-release <version>` command but looks like you did the same changes already, including the Upgrading docs. You could try the script on a new branch and compare to your changes here to be sure it's the same but looks good. Thank you.

**Comment by tagliala** [comment]
Yes, it is identical (except for the manual updates to upgrading guide)

**Review by javierjulio — APPROVED** [review]
Thanks!

**Pull request merged**
