### PR TITLE
Support for Rails 6.1

### PR DESCRIPTION
**Pull request by deivid-rodriguez**

### CODE REVIEW

**Comment by nathan-appere** [comment]
`railties` version in the gemspec probably need to be updated too.

**Comment by deivid-rodriguez** [comment]
Nice catch, yeah! I'll handle this soon.

**Comment by kwent** [comment]
Blocker for me to upgrade to 6.1 ! Thanks for your hard work guys

**Comment by manas11** [comment]
> Blocker for me to upgrade to 6.1 ! Thanks for your hard work guys

Yeah, same here. Thank you for upgrading this

**Review by javierjulio — APPROVED** [review]
Looks great, thanks! 👏🏻

**Comment by deivid-rodriguez** [comment]
Ok, I'm releasing this thing now!

**Comment by deivid-rodriguez** [comment]
Oh, I forgot we already merged the PR removing the sprockets dependency, and I wanted to ship that as 3.0.

Should we take our chances and release that as 2.9 for simplicity?

**Comment by javierjulio** [comment]
Yes I think we should ship a 2.9 release instead and leave the breaking change as a separate release.

**Comment by deivid-rodriguez** [comment]
So you mean 2.9 with only Rails 6.1 support? If we do that I need to either create a stable branch from before we merged the sprockets PR and backport this PR there, or revert the sprockets PR on master and then release.

What I was thinking is that the sprockets change we concluded it was 99% backwards compatible. Only if an application is not explicitly depending on sprockets and relying on activeadmin providing the dependency things could break, and that should be very very rare. So I figured we could cut master as it is.

**Comment by javierjulio** [comment]
Ah yes sorry I realized that after I commented. Hmm I don't think it's an issue. If you prefer to do a 2.9 release with the sprockets dependency related change I'm ok with that. 👍🏻

**Comment by deivid-rodriguez** [comment]
Ok, I'll do that then.

**Review by amirnateghi198 — COMMENTED** [review]
Update your account information for

**Pull request merged**
