### PR TITLE
Fix regression extracting HasManyBuilder

### PR DESCRIPTION
**Pull request by varyonic**
Extends a test in form_builder_spec to try to reproduce #5182  The test passes so more investigation required.

### CODE REVIEW

**Comment by varyonic** [comment]
@alexaltair I updated the spec in bc4f4b5cab00523f7559aa91bd87fdea1223c536 and it still passes.  Is your form in a Rails partial template perhaps?

**Comment by alexaltair** [comment]
@varyonic Huh. No, it's not in a partial. That test does look like the situation that fails for me.

**Comment by varyonic** [comment]
Feel free to branch and tweak the test to see if you can make it fail.  I've temporarily included a commit that prints the generated HTML.

**Comment by varyonic** [comment]
By great coincidence the test I added failed to reproduce the original reported issue but it DID detect a regression in #5196.

**Pull request merged**
