### PR TITLE
Wrap the action link text with spans that can be styled using C…

### PR DESCRIPTION
**Pull request by vraravam**
…SS to replace ther content with images/icons for better horizontal screenspace.

### CODE REVIEW

**Comment by vraravam** [comment]
@timoschilling - could you please review and merge this before 1.0.0? It would be an immense favor to get this done. I'm trying to get the following kind of UI:
icons-as-action-links

**Comment by timoschilling** [comment]
1. We will not accept HTML Strings in our code, rewrite it with arbre
2. Why do you need the span? You can replace the link text/content via css.

**Comment by vraravam** [comment]
I just realized that this is possible with the `view_link` css-style itself. The only thing missing would then be the on hover tooltip (since in my case, I am replacing the text with the image). Would you accept this PR if I removed the `span` and added the `title` attribute to the `a` tag?

**Comment by timoschilling** [comment]
yes

**Comment by vraravam** [comment]
Done - please review and merge?

**Comment by timoschilling** [comment]
please squash your commits into one, then it can be merged

**Comment by vraravam** [comment]
@timoschilling - done squashing :)

**Pull request merged**
