### PR TITLE
Arbre's version dependency update

### PR DESCRIPTION
**Pull request by astrocket**
https://github.com/activeadmin/arbre/pull/110

### CODE REVIEW

**Comment by ionut998** [comment]
Might be worth updating the other gemfiles as well
https://github.com/activeadmin/activeadmin/blob/master/gemfiles/rails_50.gemfile.lock
https://github.com/activeadmin/activeadmin/blob/master/gemfiles/rails_51.gemfile.lock
https://github.com/activeadmin/activeadmin/blob/master/gemfiles/rails_60.gemfile.lock
You should be able to just run `export BUNDLE_GEMFILE=gemfiles/rails_60.gemfile` and then `bundle update arbre`

**Comment by deivid-rodriguez** [comment]
I'm going to release the final 1.2.0 version tomorrow, so maybe we better wait and then add that in this PR?

**Comment by deivid-rodriguez** [comment]
Arbre 1.2.0 is out now. If you remove `arbre` [from the Rails 6 Gemfile](https://github.com/activeadmin/activeadmin/blob/f840c5c706967846114d28206c13bc73f53eed64/gemfiles/rails_60.gemfile#L7-L8), and then run `bin/rake bundle[update,arbre]`, that should do the trick.

**Comment by deivid-rodriguez** [comment]
Superseded by #5726. Thanks so much anyways! :heart:

**Pull request closed without merging**
