### PR TITLE
Jruby compat

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
Supersedes #3792

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
@brennovich The travis build timed out. The `-X+O` flag is too slow. I've removed it for now. The build was not failing for me without and maybe they've fixed the original issue you were having upstream...

**Comment by deivid-rodriguez** [comment]
It worked!! It only failed for Rails 3.2.22 but this Rails version is excluded from the build for MRI 2.2, so I guess you don't expect to support that combination. Since jruby-head is 2.2 compatible, I've excluded that Rails version too.

Now the build should be green, let's cross fingers.

**Comment by deivid-rodriguez** [comment]
yay! :smile:

**Comment by brennovich** [comment]
\o/

**Comment by brennovich** [comment]
Weird, I didn't look closely, but it seems that the memory leak specs were removed, otherwise they shouldn't be passing as jRuby does not have ObjectSpace emulation enabled by default (only with -X+O)

**Comment by deivid-rodriguez** [comment]
You're totally right. The specs are there but I guess they're not getting run, because running them separately fail without the flag.

I'm on it, the idea is to enable the flag for that single test only.

**Comment by deivid-rodriguez** [comment]
Ok, I think I'm now happy with this. Sorry for the `hound` noise.

Let's see what `travis` says and let me know your feedback!

**Comment by brennovich** [comment]
Wow! Great work, well documented commits :)

Thanks \o/

**Comment by timoschilling** [comment]
Good job!

**Comment by deivid-rodriguez** [comment]
Thanks!

**Comment by seanlinsley** [comment]
:heart: :heart: :heart: I'm so glad to see this finally happened

**Pull request merged**
