### PR TITLE
Add Contributor Covenant as our code of conduct

### PR DESCRIPTION
**Pull request by seanlinsley**
The purpose of adopting this code of conduct is to signal to potential contributors that this is a project where they won't be abused or attacked in any way. It also signals to everyone else that such behavior will not be tolerated.

This COC is copied from http://contributor-covenant.org/

I'll leave this PR open for a week, in the case that people have concerns with the wording.

### CODE REVIEW

**Comment by timoschilling** [comment]
I don't think that we need such a thing

**Comment by seanlinsley** [comment]
It's a proactive measure. Can you provide a reason why we shouldn't use it?

**Comment by timoschilling** [comment]
Does this prevent someone from commenting things against the CoC? No
Does this motivate someone to commit only to projects with a CoC? No
Does this stop people from saying there meaning to some else's code? I think so
Does this prevent people from committing to active admin? I think so, if I want to fix something, I don't want to read a CoC

**Comment by timoschilling** [comment]
A CoC don't stop people from writing bad thinks. Block them, ignore them, delete them or what ever ...

**Comment by seanlinsley** [comment]
> Does this stop people from saying there meaning to some else's code? I think so

Can you reword that? I'm not sure what you're saying.

> Does this prevent people from committing to active admin? I think so, if I want to fix something, I don't want to read a CoC

So don't read it.

> A CoC don't stop people from writing bad thinks. Block them, ignore them, delete them or what ever ...

A CoC gives the administrators the power to ban people, and gives others the reassurance that the administrators won't just ignore the toxic members of their community.

**Comment by timoschilling** [comment]
> > Does this stop people from saying there meaning to some else's code? I think so

> Can you reword that? I'm not sure what you're saying.

Someone writes a code, which is not good and I want to say, "Your code is bad", this can be contravene point 2 and 3 of the CoC. 

> > Does this prevent people from committing to active admin? I think so, if I want to fix something, I don't want to read a CoC

> So don't read it.

Why does we need it, if nobody should read it?

> > A CoC don't stop people from writing bad thinks. Block them, ignore them, delete them or what ever ...

> A CoC gives the administrators the power to ban people, and gives others the reassurance that the administrators won't just ignore the toxic members of their community.

We don't need a CoC to do that

**Comment by timoschilling** [comment]
The CoC is hard to understand vor not native speakers.

**Comment by seanlinsley** [comment]
> Someone writes a code, which is not good and I want to say, "Your code is bad", this can be contravene point 2 and 3 of the CoC. 

Linus Torvalds commonly uses personal attacks against potential contributors. I've never seen you do that, nor would I expect you to.

> Why does we need it, if nobody should read it?

You may not care to read it, just like people who open tickets before reading the contributing guide. That doesn't mean it shouldn't be there.

>> A CoC gives the administrators the power to ban people, and gives others the reassurance that the administrators won't just ignore the toxic members of their community.

>We don't need a CoC to do that

As I said at the beginning, this is a proactive measure to prevent a toxic culture from being created. It is a specific list of rules that maintainers can use to determine whether a person is behaving out of bounds. It also prevents misunderstandings and arguments between maintainers over whether a given act is allowable.

> The CoC is hard to understand vor not native speakers.

That's a very real problem, but isn't that already a barrier to contributing to Active Admin? If there are specific wording changes you would like to see, feel free to suggest them.

**Comment by timoschilling** [comment]
> Linus Torvalds commonly uses personal attacks against potential contributors. I've never seen you do that, nor would I expect you to.

Yes, but a CoC don't stop someone doing this. If you don't expect that from me, why do you expect it from someone else?

> You may not care to read it, just like people who open tickets before reading the contributing guide. That doesn't mean it shouldn't be there.

Ok, thats true

> As I said at the beginning, this is a proactive measure to prevent a toxic culture from being created. It is a specific list of rules that maintainers can use to determine whether a person is behaving out of bounds. It also prevents misunderstandings and arguments between maintainers over whether a given act is allowable.

The CoC doesn't make a statement about the what's ok and what's not ok.

> That's a very real problem, but isn't that already a barrier to contributing to Active Admin? If there are specific wording changes you would like to see, feel free to suggest them.

There are difference between technical and political or low english, I think I understand 99,9% of that readme, issues, pr's, but I need to read the CoC 2 times and have to look up 5 words and one sentence. And there are still thinks that I understand (I can translate into german), but I still don't know what thy mean.

**Comment by timoschilling** [comment]
BTW: some time ago I want to define rules about how ore code should look like and you are against this. Now you want rules for comments!?

**Comment by timoschilling** [comment]
If you really want a CoC, just write "don't be eval", thats something that everybody understands.
But hay thats that's the base of every community and a basic rule of being a human kind. So does we need a CoC for that? No!

**Comment by zorab47** [comment]
I like the idea of having a code of conduct. It helps show that we want to be respectful of others in the community and that unacceptable behavior will not be tolerated.

:+1:

**Comment by pboling** [comment]
I like the idea of a code of conduct because it is a mostly symbolic gesture, and symbols matter.  Yes, it adds nothing concrete, but that's hardly the point.  If it helps people to try to phrase their comments better, then great!

Mostly it **will be ignored**, and that's fine.  These sorts of protections are not for the majority.  They are to protect the **minority** and create places where they can contribute safely.

**Comment by jancel** [comment]
I'm not for or against, but interested in what spurred this on.  Is it a legal issue or something that needs to be done?  On a conservative note, I'd say leave it out.  But if we're having issues for whatever reason, then the liberal in me says do it.  

I haven't read all of the codes (conduct or not) of any library.

Is there a precedent? Does Angular do it, does Google open source do it? Twitter?  I would just follow the leader.  If people want to say harmful things, I think that's great.  At least then we know if we are making progress or there is progress to be had.

When people call me a dumbass, I just try to figure out what I did that was so stupid... and try not to do it again until tomorrow.

**Comment by pboling** [comment]
An official Code of Conduct is now a standard option for all new gems created with Bundler (which is most new gems).

**Comment by timoschilling** [comment]
@seanlinsley when you mean we need it, merge it

**Comment by timoschilling** [comment]
http://esr.ibiblio.org/?p=6918

**Comment by seanlinsley** [comment]
@timoschilling as I said before, this is a proactive measure. It sets the tone. It says that certain behaviors are not allowed, which signals to minorities (remember that the open source community is mainly white males) that they are welcome here.

Countless women have come forward saying that they've been harassed in private IRC discussions, among other places. This is an effort to ensure that they won't be harassed here.

Here are some well-known Ruby projects that have adopted this CoC in particular:
> GitLab, Diaspora, Bundler, Rails, RSpec, Rubygems, Volt, CocoaPods, Celluliod, Atom, Spree

**Comment by seanlinsley** [comment]
Companies have anti-harassment policies. This is the equivalent for open source projects.

**Pull request merged**
