### PR TITLE
(regression) Filter label can be a proc

### PR DESCRIPTION
**Pull request by WaKeMaTTa**
Label should be also consider `Procs`.

This a feature broken +v1.1.0

### CODE REVIEW

**Comment by WaKeMaTTa** [comment]
@deivid-rodriguez this PR should be backported to v1.1.0

**Comment by deivid-rodriguez** [comment]
ok! Can you open a PR?

**Comment by WaKeMaTTa** [comment]
@deivid-rodriguez yes.

**Comment by WaKeMaTTa** [comment]
@deivid-rodriguez done https://github.com/activeadmin/activeadmin/pull/5418

**Pull request merged**
