### PR TITLE
translate custom Ransack predicates

### PR DESCRIPTION
**Pull request by istana**
The issue is described here https://github.com/activeadmin/activeadmin/issues/4150 and here https://github.com/activerecord-hackery/ransack/pull/627.

### CODE REVIEW

**Comment by timoschilling** [comment]
we don't accept 3 party keys in our locales

**Comment by istana** [comment]
Ah, ok. I thought it originates from activeadmin.

**Comment by seanlinsley** [comment]
Those should be `active_admin.filters.predicates` key. For example:
```yaml
ar:
  active_admin:
    filters:
      buttons:
        filter: "تصفية"
        clear: "تفريغ التصفية"
      predicates:
        contains: "يحتوي"
        equals: "متساوي"
        starts_with: "يبدأ بـ"
        ends_with: "ينتهي بـ"
        greater_than: "أكبر من"
        less_than: "أقل من"

**Comment by seanlinsley** [comment]
Actually, they already are for English. Looks like the issue is #3958. I'm not sure I understand the problem after my quick reading of the ticket, but we're going to need to think through a solution.

**Comment by istana** [comment]
now I understand why it is a duplicate of #3958

**Pull request closed without merging**
