### PR TITLE
Switch to sassc-ruby / sassc-rails

### LINKED ISSUE #5226: [1.1 / 2.0] Implicit dependency on gem 'sass-rails'
### Expected behavior

I expect there to be some way of telling activeadmin-1.1 and activeadmin-2.0 to include a third-party .css-file.

### Actual behavior

In activeadmin-1.0, you have two ways to get this to work.

- With an `@import 'select2'`-statement in _app/assets/stylesheets/active_admin.scss_.
- With an `config.register_stylesheet 'select2.css'`-statement in _config/initializers/active_admin.rb_.

In activeadmin-1.1, an `@import`-statement that refers to a .css-file no longer works, because activeadmin switched from `sass-rails` to `sass`. Trying this anyway results in an error.

```
Sass::SyntaxError in ActiveAdmin::Devise::Sessions#new

Showing /usr/local/lib/ruby/gems/2.2.0/gems/activeadmin-1.1.0/app/views/layouts/active_admin_logged_out.html.erb where line #9 raised:

File to import not found or unreadable: select2.
Load paths:
  /mnt/c/projects/my-project/app/assets/config
  /mnt/c/projects/my-project/app/assets/images
  /mnt/c/projects/my-project/app/assets/javascripts
  /mnt/c/projects/my-project/app/assets/stylesheets
  /mnt/c/projects/my-project/vendor/assets/javascripts
  /mnt/c/projects/my-project/vendor/assets/stylesheets
  /usr/local/lib/ruby/gems/2.2.0/gems/xdan-datetimepicker-rails-2.5.4/app/assets/javascripts
  /usr/local/lib/ruby/gems/2.2.0/gems/xdan-datetimepicker-rails-2.5.4/app/assets/stylesheets
  /usr/local/lib/ruby/gems/2.2.0/gems/select2-rails-4.0.3/vendor/assets/javascripts
  /usr/local/lib/ruby/gems/2.2.0/gems/select2-rails-4.0.3/vendor/assets/stylesheets
  /mnt/c/projects/activeadmin_addons/app/assets/images
  /mnt/c/projects/activeadmin_addons/app/assets/javascripts
  /mnt/c/projects/activeadmin_addons/app/assets/stylesheets
  /mnt/c/projects/activeadmin_addons/vendor/assets/jquery_palette_color_picker
  /usr/local/lib/ruby/gems/2.2.0/gems/activeadmin-1.1.0/app/assets/images
  /usr/local/lib/ruby/gems/2.2.0/gems/activeadmin-1.1.0/app/assets/javascripts
  /usr/local/lib/ruby/gems/2.2.0/gems/activeadmin-1.1.0/app/assets/stylesheets
  /usr/local/lib/ruby/gems/2.2.0/gems/activeadmin-1.1.0/vendor/assets/javascripts
  /usr/local/lib/ruby/gems/2.2.0/gems/activeadmin-1.1.0/vendor/assets/stylesheets
  /usr/local/lib/ruby/gems/2.2.0/gems/coffee-rails-4.2.2/lib/assets/javascripts
  /usr/local/lib/ruby/gems/2.2.0/gems/formtastic-3.1.5/app/assets/stylesheets
  /usr/local/lib/ruby/gems/2.2.0/gems/jquery-rails-4.3.1/vendor/assets/javascripts
  /usr/local/lib/ruby/gems/2.2.0/gems/actioncable-5.0.6/lib/assets/compiled
  /usr/local/lib/ruby/gems/2.2.0/gems/turbolinks-source-5.0.3/lib/assets/javascripts

Extracted source (around line #1):

@import 'select2';
@import 'jquery.xdan.datetimepicker';
@import 'palette-color-picker';

@import 'inputs/numeric-range-filter';
@import 'inputs/color-picker';

Rails.root: /mnt/c/projects/my-project

Application Trace | Framework Trace | Full Trace
/mnt/c/projects/activeadmin_addons/app/assets/stylesheets/activeadmin_addons/all.scss:1
sass (3.5.2) lib/sass/tree/import_node.rb:67:in `rescue in import'
```

In activeadmin-1.1, `register_stylesheet` still works, but raises a deprecation warning.

```
DEPRECATION WARNING: Active Admin: The `register_stylesheet` config is deprecated and will be removed
in v2. Import your "select2.css" stylesheet in the active_admin.scss.
 (called from block in <top (required)> at /mnt/c/projects/my-project/config/initializers/active_admin.rb:5)
```

In activeadmin-2.0, `register_stylesheet` was removed, so there is no longer a way to include a third-party .css-file.

### How to reproduce

- Create a new Active Admin-app.
- Remove `sass-rails` from the Gemfile (it's supposed to be optional).
- Attempt to include some third-party .css-file in Active Admin, such as https://github.com/argerim/select2-rails/blob/master/vendor/assets/stylesheets/select2.css.

### Available workarounds

Add `gem 'sass-rails'` to the Gemfile of your Active Admin-app.

### Solution

Re-add 'sass-rails' as an explicit dependency of activeadmin.

https://github.com/activeadmin/activeadmin/pull/5037/files#diff-e7529ad2dc91228fecef674a9b3dffbb

### See also

https://github.com/activeadmin/activeadmin/blob/master/CHANGELOG.md#110-

https://github.com/platanus/activeadmin_addons/issues/156

https://github.com/activeadmin/activeadmin/blob/1-1-stable/lib/active_admin/asset_registration.rb

https://stackoverflow.com/questions/27170575/activeadmin-and-additional-custom-css-files

### LINKED ISSUE #5502: Ruby Sass ("sass" gem) will be end-of-life March 26th 2019 - Consider switching to "sassc-rails" or  "sassc"
See this blog post: http://sass.logdown.com/posts/7081811

And this issue over at sass-rails: https://github.com/rails/sass-rails/issues/420

The ruby implementation of sass is already designated as "deprecated", so it's *already* in maintenance mode. They will be archiving the repo and not accepting issues or pull requests after March 29 2019. So it is going to eventually get stale.

I would like to suggest this gem switch to [`sassc-rails`](https://github.com/sass/sassc-rails) or [`sassc`](https://github.com/sass/sassc-ruby), which uses the new C implementation of Sass.

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
This is some initial work to fix #5502. Something I've noticed is that this effectively drops support for `sass-rails`, so we might as well reintroduce the `sassc-rails` runtime dependency since we originally switched from `sass-rails` to plain `sass` in order to support `sassc-rails`, but now `sassc-rails` will be the only supported implementation :man_shrugging:.

Closes #5502.
Closes #5226.

### CODE REVIEW

**Comment by DeeDeeG** [comment]
By the way, I believe `sass-rails` wants to support `sassc`, but they haven't updated their progress on that since 2017:

https://github.com/rails/sass-rails/pull/349#issuecomment-300296084

**Comment by deivid-rodriguez** [comment]
Thanks for that info @DeeDeeG! In that case, I guess it's better to leave things as they are now, leaving it opened for the application to choose just in case. :+1:

**Comment by DeeDeeG** [comment]
No problem, and thank you for responding to this situation so quickly!

**Comment by deivid-rodriguez** [comment]
sassc-rails is in the process of adding jruby support, and this is green when tested against the PR adding support :+1:.

Thoughts on depending on `sassc-rails` vs depending on `sassc`?

**Comment by javierjulio** [comment]
Awesome! I checked the PR there as well. That's great news! In regard to which dependency, I'm not really sure. I have followed what other libraries do. I think if we have been fine with just including `sass` (excluding the EOL part) then perhaps good to just stick with `sassc` for now. What do you think is best?

**Comment by deivid-rodriguez** [comment]
I don't have a strong opinion, what you said makes sense, so I'll leave it as it is for now.

**Comment by javierjulio** [comment]
Sounds good then, we’ll stick with this for now thanks! Should we wait for a sassc-rails before we merge this?

**Comment by deivid-rodriguez** [comment]
Yeah, I think there's no rush :+1:

**Comment by deivid-rodriguez** [comment]
Some updates here. `sassc-rails` released a new version that dropped the `sass` dependency, but now we're waiting on a new release that fixes `jruby` support.

Also, I noticed #5226, due to the fact of depending on plain `sass` instead of `sass-rails`. So I'm tempted introduce `sassc-rails` as a runtime dependency as I suggested in the first message.

**Comment by deivid-rodriguez** [comment]
Some extra updates. Everything this was block in has been released, so this should be ready to go. I've also added `sassc-rails` as a runtime dependency and I'm waiting for confirmation that doing this fixes #5226.

**Comment by deivid-rodriguez** [comment]
I'm holding this off a bit longer, because it's unclear to me whether the `sassc-rails` will be needed or not in the future.

I [fixed `sassc` support in `sprockets` recently](https://github.com/rails/sprockets/pull/592) and now our specs pass against `sprockets` master without the `sassc-rails` dependency. This is because the main stuff provided by `sassc-rails`, [a sprockets compresor](https://github.com/sass/sassc-rails/blob/95f47ca22cc45b329b3e707326e6a7008c216488/lib/sassc/rails/compressor.rb) and [a sprockets processor](https://github.com/sass/sassc-rails/blob/95f47ca22cc45b329b3e707326e6a7008c216488/lib/sassc/rails/template.rb) are also builtin in sprockets.

So I think `sassc-rails` might end up being completely merged into `sprockets`. I propose to wait and see how `rails` handles this, and do the same.

**Comment by DeeDeeG** [comment]
Hi again!

There is a PR to make `sass-rails` a lightweight wrapper for `sassc-rails`.



- https://github.com/rails/rails/issues/32896#issuecomment-473502698
  - > We decided to make sass-rails a thin wrapper for sassc-rails, see rails/sass-rails#424
- https://github.com/rails/sass-rails/pull/424

This is only as of a day ago, so I guess it might not happen exactly that way without some further comments/consensus or something, but you know. Looks like that's the plan so far.

**Comment by timoschilling** [comment]
good work 🎉 👍

**Comment by deivid-rodriguez** [comment]
Thanks!! Let's do this!

**Comment by Calamari** [comment]
Woohoo :tada:

**Comment by javierjulio** [comment]
Awesome thanks! Curious why didn’t we use sass-rails instead? From what I understood that would continue to get updated to avoid issues or perhaps the plan for that gem is to slowly get users to switch to sassc-rails instead?

**Comment by deivid-rodriguez** [comment]
Yeah, I had the same doubt. I asked in the rails repo in a couple of related issues, but nobody answered.

The way I see it, `sass-rails` is getting abandoned. It's currently [just a wrapper around sassc-rails](https://github.com/rails/sass-rails/blob/8dbe4dcf69790e3a5691dab7a61e6fff429feaaf/lib/sass-rails.rb#L1).

**Pull request merged**
