### PR TITLE
force usage of jQuery 2 from jquery-rails

### PR DESCRIPTION
**Pull request by duksis**
was debugging weir behavior of active admin what was caused by requiring jquery 3
I would suggest explicitly to require jquery 2 until jquery 3 is fully supported.

### CODE REVIEW

**Comment by timoschilling** [comment]
can some confirm problems with ActiveAdmin an jQuery3?

**Comment by swrobel** [comment]
I can confirm that checkbox multi-selection and enabling of batch actions do not work for me with jQuery 3.x. They work fine with 2.2.4

**Comment by timoschilling** [comment]
I need to revert this, until jquery-rails 4.2 is released.

**Comment by swrobel** [comment]
@timoschilling what's the issue w/ jquery-rails < 4.2?

**Comment by timoschilling** [comment]
@swrobel I updated my last commend. 
jquery-rails < 4.0, has no file named jquery2 and jquery-rails > 4.0 don't support rails < 4.2.

**Comment by timoschilling** [comment]
There is something that I don't understand: The file jquery only contains jquery 1.x and never jquery 2 or 3. That means that the jquery problems inside of AA has to be a other source.

**Comment by swrobel** [comment]
@timoschilling I'll explain how I encountered this issue on a Rails 4.2 app: I am using jquery from rails-assets (I have since stopped doing this) which apparently overrides the jquery-rails-provided version when doing `#= require jquery`. Hence, ActiveAdmin ended up using jquery 3. I don't necessarily endorse this fix, I just wanted to chime in and mention that I could verify the jquery 3 issue. I suppose the true issue is, why is AA incompatible with jquery 3?

**Comment by timoschilling** [comment]
@swrobel ok, I understand.
@duksis who is your setup?

**Comment by duksis** [comment]
@timoschilling I'm on rails (4.2.6) and jquery-rails (4.1.1)

**Comment by timoschilling** [comment]
@duksis please execute this in your Browser console `$.fn.jquery`

**Comment by timoschilling** [comment]
I have rails 5, jquery-rails 4.1.1 and it use jquery 1.12.1

**Comment by duksis** [comment]
$.fn.jquery
"2.2.1"
I'm using activeadmin from my fork

**Comment by swrobel** [comment]
@duksis so, the question is, how did you end up using jQuery 3 in your app?

**Comment by duksis** [comment]
@swrobel yes sorry - was a long week
reverted my app back to the broken state:
rails (4.2.6)
jquery-rails (4.1.1)
jquery-ui-rails (5.0.5)
select2-rails (4.0.2)
activeadmin (1.0.0.pre2)
activeadmin-select2 (0.1.8)

on my local machine active admin is requiring "2.1.4" but on heroku it's "3.1.0"
https://active-admin-jquery-3.herokuapp.com/admin/login
don't know how

**Comment by timoschilling** [comment]
@duksis can you publish the source code of https://active-admin-jquery-3.herokuapp.com?

**Comment by duksis** [comment]
not without cleanup - I'll try to do that today

**Pull request merged**
