### PR TITLE
Fixed some JS initializers to run on turbolinks page:load also

### PR DESCRIPTION
**Pull request by nextbyte**

### CODE REVIEW

**Comment by nextbyte** [comment]
https://github.com/activeadmin/activeadmin/issues/3744

**Comment by timoschilling** [comment]
You are sure that the 3 files are all related files? @rodrigoddalmeida has reported the problem for the `has_many.js` too.

**Comment by timoschilling** [comment]
But :+1: good work

**Comment by nextbyte** [comment]
I tested has many and it works fine. It might be needed in the newly added per_page.js.coffee also, I didn't see it was added before I submitted the PR. I'll check.

**Comment by rodrigoddalmeida** [comment]
I'll just comment that, even if adding the handlers to respond to _page:load_ works, it may not be a reasonable way to do it since it's not a 'default' event name. Solving it like this might cause more maintenance of said code (i.e Turbolinks changing its event names).

Since activeadmin is already highly reliant on jQuery, I do recommend using [kossnocorp/jquery.turbolinks](https://github.com/kossnocorp/jquery.turbolinks) when using Turbolinks, anyways.

Also, there are callbacks being bound to the _document_ and being delegated to the wanted selector. Those cases should be out of the _ready_ event function to not be prone to rebound (called more than once).

**Comment by nextbyte** [comment]
I don't know if it is okay to force users to use jquery.turbolinks in order to make turbolinks work with AA, jquery.turbolinks is provided as an workaround and rails >= 4 only includes the turbolinks gem by default.

Yes, I know there are callbacks that shouldn't be set more then once. From my tests I didn't see any issue like that with the changes I've made.

**Comment by timoschilling** [comment]
I share @nextbyte's point of view

**Comment by rodrigoddalmeida** [comment]
To be fair, it's not about forcing the use of the jquery.turbolinks. The thing is: being neutral and sticking to the default (JS and jQuery) pattern is easier and it'll still work. The code in question is not optimal, with or without Turbolinks.

It could be also solved by adding the jquery.turbolinks asset to the project the same way jQuery is, as a dependency (which I think is not the case at all).

So, I think, it all boils down to AA actively supporting Turbolinks or not, and why should it be supported instead of other options.

**Comment by nextbyte** [comment]
When you create an new rails 4 application turbolinks is added and enabled by default. I know it is not enabled by default in active_admin.js now also but I think users would expect to get it with AA also since it's part of default rails now.

Also with the changes suggested it still works fine even if you don't enable turbolinks so I don't see what is the problem if we support it. I think is should be supported because it is used by default in rails now and I don't know other similar options that we could support.

**Comment by timoschilling** [comment]
@nextbyte :+1:

**Pull request merged**
