### PR TITLE
Revert "remove kaminari theme"

### PR DESCRIPTION
**Pull request by killthekitten**
Reverts activeadmin/activeadmin#3653

The reason is #1126

### CODE REVIEW

**Comment by dmitry** [comment]
:+1: good point.

**Comment by killthekitten** [comment]
@timoschilling any thoughts?

**Comment by timoschilling** [comment]
I understand why it was in, but I still think it should be keep out. The reason is why should we carry a copy of the template with us, if there is a template in kaminari. I know it can be happen that the app overwrites this template, but then the developer can simply use this template as a theme.

Some equal examples:
- If you turn of `include_all_helpers`, you need to include the devise helper by your self (#3061)
- If you overwrite a bourbon mixin, you break the activeadmin css (is happened to me)
- If you use redcloth it breaks the devise views (#3777)
All cases can be fixed by activeadmin, but if we care about all thinks we have a massive code base which is hard to maintain.

Thats why my opinion ist *keep it simple as it can*.

Maybe @seanlinsley has a other opinion, then we can talk about it.

**Comment by killthekitten** [comment]
@timoschilling that's one of the reasons, why `ActiveAdmin` development is abandoned by community. There always comes a moment, when it's much simpler to bootstrap an admin interface from scratch than to deal with inexplicable behaviors of something so called `Ruby on Rails framework for creating elegant backends for website administration`.

Tool should be predictable and respect the real world use cases. Look around, we're using `ruby` and `rails` here. 

That's about pretty much everything:
https://github.com/activeadmin/activeadmin/issues/3846

**Comment by timoschilling** [comment]
That you link to #3846 shows your problem, you want a autonomic full featured drop in framework. That's not possible without self building all components. Thats why we use third party gems in activeadmin. If you use components you need to deal with there behavior. You can't start fixing the bug of component A in component B, thats what you want in #3846. Nearly the same here, your app breaks the default kaminari theme, so you need to fix it in your scope, for example by naming your theme and not overwriting it.

**Comment by jhanggi** [comment]
I've just run into this same issue. The front end of our site has a custom template built by our designers. Now the pagination styling in ActiveAdmin is busted.

Kaminari does have built-in templates, which I understand the desire to use them so you don't need to maintain your own. 

What would you think about exposing the Kaminari theme name as a configuration option? That way, you don't have to maintain your own versions, and those of us who do need to override it for the front-end have a way to keep a sane default. Or is there a way to force AA to use the gem's version of the templates?

Thanks.

**Comment by timoschilling** [comment]
I have already tried to force the loading of the gem template version. But actually that is not supported by kaminari and/or ActionView.

I have tried this:
```ruby
Kaminari::Engine.paths["app/views"].first
# => "/Users/captainhagbard/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/kaminari-0.16.3/app/views"
```

**Comment by javierjulio** [comment]
@timoschilling the Kaminari maintainer (amatsuda) seems very active on accepting pull requests. Should we file an issue? Or have something we could submit? I can try to help.

**Comment by killthekitten** [comment]
@javierjulio you can try to add an option of using gem's template without adding it to project

**Comment by timoschilling** [comment]
@javierjulio sure, it would be nice if kaminari has a option for that.

**Comment by javierjulio** [comment]
@timoschilling @killthekitten this must be [the pull request](https://github.com/amatsuda/kaminari/pull/668) we need to resolve this issue! Adds a path prefix option for the Kaminari views generator. Since I'm doing the CSS overhaul I'd like to modify the ActiveAdmin pagination setup or would we prefer to just keep the default?

**Comment by whatcould** [comment]
Not sure why we couldn't just leave the paginatinon templates in! Almost two years later and there's still no way to override the pagination in my app without breaking the ActiveAdmin pagination, short of specifying it every time.

I get arguments about maintainability, but if that's what you're worried about, first of all, these templates don't really change. But also, it's easier to maintain the styles if you freeze the HTML by copying the templates!

**Pull request closed without merging**
