### PR TITLE
Update es.yml

### PR DESCRIPTION
**Pull request by kennym**
Provide spanish translations for `comments.created_at` and `comments.updated_at`

### CODE REVIEW

**Comment by timoschilling** [comment]
`updated_at

**Comment by timoschilling** [comment]
`updated_at` is not used by the `en.yml` so we can't add it for `es.yml`. Please update you PR to add only `created_at` or create a new PR.

**Comment by kennym** [comment]
@timoschilling done.

I wonder why we don't add `updated_at` to the local `en.yml`?

**Comment by timoschilling** [comment]
Can you please squash both commits and force push your branch.
`updated_at` is not needed anywhere, so it is not added.

**Comment by kennym** [comment]
@timoschilling done! :)

**Pull request merged**
