### PR TITLE
Fix jruby build and refactor spec env

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
Yesterday I was working on getting jruby green again. I achieved my goal but this branch has a bunch of unnecessary/unrelated changes, so this is not ready yet.

Just opening this as a WIP PR to make @javierjulio happy :)

### CODE REVIEW

**Comment by javierjulio** [comment]
@deivid-rodriguez haha nice! I'm going to merge in #5496 for you so you can rebase here and cut this down.

**Comment by deivid-rodriguez** [comment]
Thanks! :smiley:

**Comment by deivid-rodriguez** [comment]
Superseded by #5520. Some of the changes in here, I think they're good improvements, but I'll propose them separately.

**Comment by deivid-rodriguez** [comment]
I opened PRs for the stuff here that I thought we could use. Removing the branch!

**Pull request closed without merging**
