### PR TITLE
Fix #5890 conflicts between meta_tags and Tag model

### LINKED ISSUE #5890: Conflict between meta_tags config and Tag model
First of all, thanks for this amazing gem. I'm new to Rails and this has been invaluable for me.

Now about that bug : when I visit `/admin/tags/:id` I can see a Tag object address printed out in the web page. See first line before header in the attached screenshot.

Screenshot 2019-10-18 at 15 36 57

When inspecting the page source it seems the culprit is linked with meta tags handling. Try searching for `0x00007fb49d066a18` in the following excerpt : 

```
<!DOCTYPE html><html lang="en">
  <head>
    <title>test | My App</title>
<link rel="stylesheet" media="screen" href="/assets/active_admin.self-df2f0b5617ac0f32412df760ed54f228f5b7db311fb640fed3c0926531032ff3.css?body=1" /><link rel="stylesheet" media="print" href="/assets/active_admin/print.self-5d2debdb5d662c201d203d63ad601036a4ce6dced51057e070dddbd4ec256d27.css?body=1" />#&lt;Tag:0x00007fb49d066a18&gt;<script src="/assets/jquery3.self-e200ee796ef24add7054280d843a80de75392557bb4248241e870fac0914c0c1.js?body=1"></script>
<script src="/assets/jquery-ui/version.self-c8e3d1203da26ea7efdf83c1eabb3f0ba55cb68e463f5ccf0d77bd15ce6a8e61.js?body=1"></script>
<script src="/assets/jquery-ui/keycode.self-ad63cd20acf49dd333bbbc537454d7d475bd610eb5b88de0dca009f0c3d314b1.js?body=1"></script>
``` 

This lead me to check how I configured meta tags in `config/initializers/active_admin.rb` :

```
  config.meta_tags = { viewport: 'width=device-width, initial-scale=1' }
  config.meta_tags_for_logged_out_pages = { viewport: 'width=device-width, initial-scale=1' }
```

And bingo, when I remove those two lines the bug disappears. I figure there is some namespacing issues on some variables, but I just started Rails and wouldn't know where to being.

Active Admin version is 2.4.0, Rails is 6.0.0 (was able to reproduce on 5.2.3 too) 

Here is a sample app reproducing the problem :
[my-app.zip](https://github.com/activeadmin/activeadmin/files/3744175/my-app.zip)

Thanks for considering, and if you have any idea for a workaround that would be great!

### PR DESCRIPTION
**Pull request by micred**
Fix #5890 conflicts between meta_tags and Tag model.
Please review the fix.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
Hello :wave:! Thank you so much for fixing this :heart_eyes:.

I tried to reproduce this issue with the following cucumber feature, and it still reproduces, so I think we're missing something? There's something wrong with either my scenario or this fix :thinking:.

```diff
diff --git a/features/meta_tags.feature b/features/meta_tags.feature
index f94e24d66..53c399d5f 100644
--- a/features/meta_tags.feature
+++ b/features/meta_tags.feature
@@ -19,3 +19,11 @@ Feature: Meta Tag
     Given I am logged in
     When I am on the dashboard
     Then the site should contain a meta tag with name "author" and content "My Company"
+
+  Scenario: Meta tags are not confused with a Tag model
+    Given a show configuration of:
+    """
+      ActiveAdmin.register Tag
+    """
+    Then I should not see "#<Tag:0x"
+    Then the site should contain a meta tag with name "author" and content "My Company"
```

**Comment by deivid-rodriguez** [comment]
```diff
diff --git a/lib/active_admin/views/pages/base.rb b/lib/active_admin/views/pages/base.rb
index 11755acf7..996d20ec3 100644
--- a/lib/active_admin/views/pages/base.rb
+++ b/lib/active_admin/views/pages/base.rb
@@ -33,7 +33,7 @@ module ActiveAdmin
             end
 
             active_admin_namespace.meta_tags.each do |name, content|
-              text_node(tag(:meta, name: name, content: content))
+              text_node(meta(name: name, content: content))
             end
 
             active_admin_application.javascripts.each do |path|
```

This patch seems to fix the issue. Can you try it on a real application?

**Comment by micred** [comment]
It works, but now it can be confused with a model named Meta 😅

**Comment by micred** [comment]
sure! great, thank you @deivid-rodriguez

**Pull request closed without merging**
