### PR TITLE
#5260 show pagination only if paginate config is true

### PR DESCRIPTION
**Pull request by kazu9su**
I updated the pagination behavior to display pagination only if paginate config is true.
#5260

### CODE REVIEW

**Comment by varyonic** [comment]
I thought @emilong provided a test you would want to include here.

**Comment by kazu9su** [comment]
Got it. I updated a test.

**Comment by varyonic** [comment]
@emilong provided two versions of his test: he suggested not adding the second one because it added > 2 minutes. Which one did you use?

**Comment by kazu9su** [comment]
@deivid-rodriguez 
I suppose that how many records display per page is defined by per_page option.

**Comment by deivid-rodriguez** [comment]
@kazu9su But aren't we preventing the whole collection from being rendered here? Is that really what we want?

**Comment by kazu9su** [comment]
@deivid-rodriguez 
I guess you expect like below but I think it is better to discuss about this feature with others.

```ruby
paginate         = config.fetch(:paginate, active_admin_config.paginate)

if paginate
  per_page         = config.fetch(:per_page, active_admin_config.per_page)
  paginated_collection(collection, entry_name:       active_admin_config.resource_label,
                                   entries_name:     active_admin_config.plural_resource_label(count: collection_size),
                                   download_links:   download_links,
                                   paginator:        paginator,
                                   per_page:         per_page,
                                   pagination_total: pagination_total) do
    div class: 'index_content' do
      insert_tag(renderer_class, config, collection)
    end
  end
end
```

**Comment by deivid-rodriguez** [comment]
To clarify my expectations, I completed the specs with the number of posts I expect to see in each situation:

```diff
diff --git a/features/index/pagination.feature b/features/index/pagination.feature
index 7cd1171a..06f13844 100644
--- a/features/index/pagination.feature
+++ b/features/index/pagination.feature
@@ -10,6 +10,7 @@ Feature: Index Pagination
     When I am on the index page for posts
     Then I should see "Displaying all 20 Posts"
     And I should not see pagination
+    And I should see 20 posts in the table
 
   Scenario: Viewing index when multiple pages of resources exist
     Given an index configuration of:
@@ -19,6 +20,7 @@ Feature: Index Pagination
     Given 31 posts exist
     When I am on the index page for posts
     Then I should see pagination with 2 pages
+    And I should see 30 posts in the table
 
   Scenario: Viewing index with a custom per page set
     Given an index configuration of:
@@ -31,6 +33,7 @@ Feature: Index Pagination
     When I am on the index page for posts
     Then I should see pagination with 2 pages
     And I should see "Displaying Posts 1 - 2 of 3 in total"
+    And I should see 2 posts in the table
 
   Scenario: Viewing index with pagination disabled
     Given an index configuration of:
@@ -42,6 +45,7 @@ Feature: Index Pagination
     Given 31 posts exist
     When I am on the index page for posts
     Then I should not see pagination
+    And I should see 31 posts in the table
 
   Scenario: Viewing index with pagination disabled and a collection larger than max per page
     Given an index configuration of:
@@ -54,6 +58,7 @@ Feature: Index Pagination
     Given 31 posts exist
     When I am on the index page for posts
     Then I should not see pagination
+    And I should see 31 posts in the table
 
   Scenario: Viewing index with pagination_total set to false
     Given an index configuration of:
@@ -69,7 +74,9 @@ Feature: Index Pagination
     Then I should see "Displaying Posts 1 - 10"
     And I should not see "11 in total"
     And I should see the pagination "Next" link
+    And I should see 10 posts in the table
 
     When I follow "Next"
     Then I should see "Displaying Posts 11 - 11"
     And I should not see the pagination "Next" link
+    And I should see 1 post in the table
```

This PR breaks the cases where pagination is disabled. In my opinion disabling pagination is useful when you expect a very low total number of elements for a resource, but I never expect disabling pagination to stop rendering the collection. If I want that, it's better to remove the whole index page!

**Comment by kazu9su** [comment]
As I investigated, I realized current implements based on pagination.
Probably we should discuss changing base implements or not.
So I close this PR now.

**Pull request closed without merging**
