### PR TITLE
Fix renamed resources and optional `belongs_to`

### LINKED ISSUE #3647: optional belongs_to for renamed active_admin resources creates incorrect url helpers
this code will raise exception

``` ruby
ActiveAdmin.register RegionCity, as: 'City' do
  belongs_to :country, parent_class: RegionCountry, optional: true
  navigation_menu :default
```

if belongs_to is optional url helpers are created with use of polymorphic_path and polymorphic_link methods.
This methods don't know anything about resource renaming in active admin.
when trying to open "/admin/countries/3/cities" we get:

```
undefined method `new_admin_region_country_region_city_path' for Admin::CitiesController
```

i think activeadmin need to override polymorphic_path method

I created small test project that shows this error:
https://github.com/senid231/activeadmin_test_belongs_to

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
I still want to have another look since I think there might be a bug in the resource <-> model matching part when a resource is renamed different in different namespaces.

But I think it's looking good!

Supersedes #5823.
Fixes #3647.
Closes #5483.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
I fixed the mentioned issue, and now this should be ready to merge. I want to do some squashing and add @ndbroadbent's authorship to the commits, but this is good for an initial review.

**Comment by javierjulio** [comment]
@deivid-rodriguez sorry, I'm not sure I can help much here. I'm not familiar with the nested/belongs_to feature. I don't use it.

@Fivell sorry to bother, would you have some time to review this? GitHub is suggesting you as a recent editor of these files.

@Kris-LIBIS are you able to look at this and try it out too? Would help to get your review if you can. Thanks!

**Comment by deivid-rodriguez** [comment]
No problem @javierjulio!

@ndbroadbent (author of the PR that first got this working) and @senid231 (author of the original issue) might also be helpful reviewers.

**Comment by Fivell** [comment]
hello @deivid-rodriguez  @javierjulio , 
 As I can remember this  Bug report has some more examples to check than we have in this PR,  https://gist.github.com/senid231/0dcfc8b89eb0234ba5cb5ac66fec5be7 
I think its better to run it against this branch before merging

**Comment by deivid-rodriguez** [comment]
Thanks @Fivell, I didn't notice that. I'll run that bug report template against this branch and see if it's worth adding some extra coverage :+1:.

**Comment by Kris-LIBIS** [comment]
IMHO I think I have covered that use case by namespacing the Blog::User in the current feature. What the original author's (@ndbroadbent) test case did not cover was when both parent and child of the belong to are renamed and that is what my test case and @senid231 's test case cover. But of course, there is no harm in running the test in the gist. I have good hopes that it will pass with this fix.

**Comment by deivid-rodriguez** [comment]
Some heads up here. I run the bug report template and it fails 2 tests against this PR (against 4 failures against master).

I have coded an extra fix for those 2 failures, but I still want to add coverage for it inside our specs.

**Comment by deivid-rodriguez** [comment]
Hopefully it's ok now.

I didn't add more coverage per se, what I did was to modify the previous cucumber feature to look more like the bug report template. After I did that, the same issues the bug template was showing reproduced.

First one, not being able to infer the correct parent class to retrieve records from:

```
    And I click "Author Articles"                                 # features/step_definitions/index_views_steps.rb:1
      undefined method `find' for nil:NilClass (NoMethodError)
      ./lib/active_admin/resource_controller/data_access.rb:74:in `scoped_collection'
      ./lib/active_admin/resource_controller/data_access.rb:57:in `find_collection'
      ./lib/active_admin/resource_controller/data_access.rb:44:in `collection'
      ./lib/active_admin/resource_controller/streaming.rb:12:in `index'
      ./features/step_definitions/index_views_steps.rb:2:in `/^I click "(.*?)"$/'
      features/renamed_resource.feature:66:in `And I click "Author Articles"'
```

Fixed that by passing the correctly renamed class to inherited_resources's `belongs_to` helper.

After that, another issue showed up where the parent class was not being properly "translated" before calling the polymorphic route helpers:

```
    And I click "Author Articles"                                 # features/step_definitions/index_views_steps.rb:1
      undefined method `new_admin_user_article_path' for #<Admin::ArticlesController:0x000055b6ee43c7b8>
      Did you mean?  new_admin_article_path
                     new_admin_user_password_path
                     new_admin_author_article_path
                     new_admin_user_session_path (ActionView::Template::Error)
      ./lib/active_admin/resource_controller/polymorphic_routes.rb:12:in `polymorphic_path'
```

Fixed that it by looking at the parent renamed resource to do the mapping so that the polymorphic helpers generate the correct route.

**Comment by Kris-LIBIS** [comment]
I checked it in my application and it still works. 
@deivid-rodriguez I would prefer if you would reinstate my namespaced parent test case in the features though as apparently it is a different case. Just to make sure it will not break in the future.

**Comment by deivid-rodriguez** [comment]
I didn't like the previous scenario because it was quite confusing (it renamed models as already existing models), and it also failed to detect at least two issues the bug report template detected. And I don't think namespaced models are directly involved in this issue anyways?

**Comment by deivid-rodriguez** [comment]
I'll land this now. Thanks everyone, hopefully `belongs_to` is a bit friendlier now :)

**Pull request merged**
