### PR TITLE
5090: improve download links to deal with collection

### PR DESCRIPTION
**Pull request by leonardoprg**
Hey Guys, @urkle @Fivell 

I'm opening this PR, following #5090 

It's still in progress, (and missing tests) but I did open to discuss the code, and ask about two points.

1 - `[:admin, collection.name.constantize]`, I think hardcoded `:admin` here is not a good deal, is any helper that I can get default namespace/scope routes? 
I tried `ActiveAdmin.application.router...` but I not able to found any helper that returns it,
also I saw that `ActiveAdmin.application.default_namespace` returns `:admin` but not sure if it is related to routes or folder.

2 - I'm not sure about the use of ` params: collection.where_clause.to_h`, should we just get for `foreign_keys`? should we merge it with `request.query_parameters` ?, and, fore sure we need to apply Ransack protocol here.

let me know any suggestion/question/etc.. about code

Thanks

### CODE REVIEW

**Comment by sposinff** [comment]
Without having looked at the specific code, it seems to me that the export works on an `index`, but not a `show`. There is probably some abstracted method that uses at `resources`, but on a show that object does not exist. So my thought... is it possible to pass resources to the csv builder?

**Comment by leonardoprg** [comment]
well, works on an index is not necessarily true, the problem is `export links` are generated using `url_for` and it works well on index (from resource for example), but if you try to put a resource table in `dashboard/index` for example, it will generate export links to `dashboard#index`,
my fix is to when generate links take in consideration the `resource`, in this way, even you put a resource table in `dashboard#index` for `User`, it will generate links to export `user#index`.

**Comment by sposinff** [comment]
`dashboard/index` is a `ActiveAdmin.register_page` which is different than `ActiveAdmin.register`. By index, I was referring to a `resource` index.

**Comment by javierjulio** [comment]
This could use a rebase to see if CI passes.

**Pull request closed without merging**
