### PR TITLE
Cut 2.0.0

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
I think we're ready to cut 2.0.0, but I'd like to wait a bit on #5744 and #5745, to make sure there's no actual regression in 2.0.0.rc2, and both issues were due to the bad arbre release.

### CODE REVIEW

**Comment by javierjulio** [comment]
Sounds good, thanks again David!

**Comment by deivid-rodriguez** [comment]
Ok. So no regressions in the end, so let's do this!

**Comment by deivid-rodriguez** [comment]
I released the final version! :+1:

**Comment by javierjulio** [comment]
Awesome thanks David!! 👏🏻

**Pull request merged**
