### PR TITLE
4230 search status name on filter sidebar

### PR DESCRIPTION
**Pull request by marcomd**
Add search status panel name in I18n #4230 

- [x] refactor `search_status.headline` to `search_status.current_scope` (all yml )
- [x] added new tag `search_status.headline` to :gb: and :it: yml

### CODE REVIEW

**Comment by timoschilling** [comment]
you have a formating problem in the [it.yml](https://github.com/marcomd/activeadmin/blob/4230_search_status_name_on_filter_sidebar/config/locales/it.yml#L35) and [en.yml](https://github.com/marcomd/activeadmin/blob/4230_search_status_name_on_filter_sidebar/config/locales/en.yml#L35).

**Comment by marcomd** [comment]
The usual skirmishes between windows and unix, sorry

**Comment by marcomd** [comment]
Ok all tests passed, let me know if the updated spec is ok

**Comment by marcomd** [comment]
Close #4230

**Comment by seanlinsley** [comment]
The code now relies on both the `headline` and `current_scope` translations, but for the vast majority of translation files are now missing `headline`. @timoschilling I personally wouldn't have accepted this PR without the new translations, because it means that anyone who upgrades whose app isn't set up to use English or Italian ends up with a substandard experience.

I feel like it should be standard that any PR that modifies translations should ensure that existing translation files aren't left broken.

It's not even something that has to take a long time to do, since Google spreadsheets have a function to automatically translate phrases: http://www.labnol.org/internet/google-translate-for-spreadsheets/10086/

**Comment by timoschilling** [comment]
This PR hasn't broke any translation! This PR just has renamed a translation and has add a new one.
The only think which is confusing was, that we have renamed `headline` to `current_scope` and have add a new `headline` key. That look like we have broke the old translations, but we don't.

BTW: #4304 has add the missing key for all locals

**Comment by seanlinsley** [comment]
The problem is as you said: this PR renamed `headline` to `current_scope`, and then reused `headline` for another purpose. So any language that didn't have a `headline` translation added by this PR was effectively broken.

#4304 helps, but it doesn't cover all languages. For example: [`de.yml`](https://github.com/activeadmin/activeadmin/blob/master/config/locales/de.yml#L34) is missing the new translation.

**Comment by timoschilling** [comment]
We have many key with are missing in different languages

**Comment by timoschilling** [comment]
`de.yml` has now the key

**Pull request merged**
