### PR TITLE
rework displaying current scope and filters in active filters section

### LINKED ISSUE #4899: Missing translations in filter 'current_filters' section.
Hello,
I know that the translations issue at the search_status section has been addressed, however, I reckon there are a few issues remaining.
I do manage to translate all the `search_status` fields in my language (greek), but I don't get the field names and some other things translated. See the screenshot:

image

The green arrow shows the field name translated in the filter form.
However, a little lower, in the current_filters section, the field name does not get translated.
Also, I'm struggling to find where is the translation for the scope results (ALL or anything else).

I know I need not praise, but there has been some seriously greatly done work here, this is one of the most helpful tools one can get. Congrats.

Anyway, any help will be appreciated. Thanks

### PR DESCRIPTION
**Pull request by Fivell**
- use ```DataAccess#current_scope``` method instead of ```ActiveAdmin::Filters::Active#scope``` since ```current_scope``` returns scope object which  supports localisations, dynamic names and everything else
 - display current_scope if at least 1 was declared
- added css classes for current filters and scopes for easy customisation and testing
- refactor ```ActiveAdmin::Filters::Active```
- use ransack condition object instead of request params to better handling current filters
- use translations for active filters, see ```ActiveAdmin::Filters::ActiveFilter#label```
- display related model names by ids instead of ids  see ```ActiveAdmin::Filters::ActiveFilter#values``` +  rendering current filters using pretty_format helper 

[closes #4899, #4859, #4943, #3902, #4214]

### CODE REVIEW

**Comment by Fivell** [comment]
this requires some specs

**Comment by Fivell** [comment]
@stasou , @momolog , would be nice if  you can try and make feedback

**Comment by Fivell** [comment]
@varyonic , @deivid-rodriguez , @timoschilling , @ccallebs  take a look please

**Comment by momolog** [comment]
@Fivell Will do so tonight.

**Comment by momolog** [comment]
@Fivell Looks very promising. 
I unfortunately see wrongly escaped HTML and untranslated values. See screenshot:

filter test

Also, for **relational** filters (the ones that get linked) the word "gleicht" ("equals") is missing, which is a bit inconsitent.

**Comment by Fivell** [comment]
@momolog , thanks, can you show declaration of status filter ?

**Comment by momolog** [comment]
`filter :state, :as => :select, :collection => Rental.aasm.states.map{|s| [I18n.t("state.#{s}"), s]}`
Is this ad-hoc providing of the translations the culprit?

**Comment by Fivell** [comment]
@momolog , understood,
>> Is this ad-hoc providing of the translations the culprit?

Yes, I don't know how to support custom translations from collection block. Any possibility to use relational filter here?

**Comment by Fivell** [comment]
@momolog  looks like states is just custom array, not an activerecord collection ?

**Comment by momolog** [comment]
@Fivell Yep, just [AASM](https://github.com/aasm/aasm) states defined in the state machine part of the model.

**Comment by Fivell** [comment]
@momolog , I added one more commit 
>>I unfortunately see wrongly escaped HTML and untranslated values 
not it should display just name

>> Also, for relational filters (the ones that get linked) the word "gleicht" ("equals") is missing, which is a bit inconsitent.

added predicate, check please.


But there is not support for translating filter values, have no idea about clean implementation of this

**Comment by Fivell** [comment]
@momolog , ping

**Comment by momolog** [comment]
@Fivell 
>> I unfortunately see wrongly escaped HTML and untranslated values
> now it should display just name
The markup is gone, but so is the (arguably very useful) linking. If the relations are not linked anymore, the whole panel is basically showing the exact same info as the panel above ...

>> Also, for relational filters (the ones that get linked) the word "gleicht" ("equals") is missing, which is a bit inconsitent.
> added predicate, check please.
works fine now.

> But there is not support for translating filter values, have no idea about clean implementation of this
ok

**Comment by Fivell** [comment]
@momolog ,
>>the whole panel is basically showing the exact same info as the panel above .
not sure what do you mean

**Comment by momolog** [comment]
@Fivell I mean that I vote for **linking** the relations again (just without escaping the HTML).

Now there is a filter selection panel that shows my filter choices. And under that there is the filter summary, showing *the same filter choices* as well. The added value of the lower panel would be the links.

**Comment by stasou** [comment]
I am not being able to catch any difference in behavior. I am posting a more comprehensive workaround in the original issue tab, which engulfs appearance of translated Enum fields, References, References by join table etc.

**Comment by Fivell** [comment]
@stasou , are you talking about https://github.com/activeadmin/activeadmin/issues/4899#issuecomment-292722906 ? 
or you're going to create PR ?

**Comment by stasou** [comment]
No, I am not creating a PR. I am not sure how to form it, I am just following up on my comment.

**Comment by Fivell** [comment]
@varyonic , this is what I suggest to merge.

**Comment by varyonic** [comment]
Might want to add #3958 to the close list.  Any feedback from @k3rni or @shoroh?

**Comment by Fivell** [comment]
@varyonic, this PR at least contains some specs for active filters feature,  there were almost none specs for this, I still do think there are a lot of cases that are not covered and might now work, however later it will be  easier to fix them, let's merge it and allow people to test it from master.

**Comment by stasou** [comment]
Good work with the latest merge (d941aaa). Some issues still remain, namely the following caught my eye:
- Translating the predicate fails (it always displays "contains", "eq", etc)
- Using Active Record Enum fields, there is no transformation (it displays numeric value instead of text value)

Good work though. Thank you guys.

**Comment by Fivell** [comment]
@stasou , predicates are translated with ransack itself.
references:
https://github.com/activerecord-hackery/ransack/blob/381a83cebeb4222d8b1772cd63116db58003e262/lib/ransack/translate.rb#L14
and 

https://github.com/activeadmin/activeadmin/blob/d941aaa88c6e9011f7e9d1c7d85b2cd871160f0f/lib/active_admin/filters/active_filter.rb#L61

**Comment by stasou** [comment]
@Fivell I confirm that adding ransack keys to localization solves the predicates translation issue. Thank you.

As for the enums, I comprehend that this is a far reach and it implies adding translation keys where they should probably not exist, among perhaps some other things, so I am not insisting on this one. I can quite easily override functionality to my personal needs, without the need to pull the project... In other words, everything is fine, I am 100% covered.

Concluding this, I would like to thank everyone in the team for your support. Keep up the good work.

**Pull request merged**
