### PR TITLE
Handle table prefix & table suffix for ActiveAdminComment model

### LINKED ISSUE #5093: table name prefix & suffix not taken into account for active_admin_comments
Because I'm currently working with a legacy database, I have setup a table name prefix in `config/application.rb`.

```ruby
ActiveRecord::Base.table_name_prefix = 'prefix_'
```

It appears that ActiveAdmin does not pickup on that, which result in a Mysql error when trying to display the index page of the `Comment` resource or any individual resources:

### Expected behavior

ActiveAdmin should detect that a prefix has been set on ActiveRecord and use it when retrieving admin comments.

### Actual behavior

I think that since `table_name` is set `/lib/active_admin/orm/active_record/comments/comment.rb` the `table_name_prefix` is discarded.

```
ActiveRecord::StatementInvalid in Admin::CommentsController#index
Mysql2::Error: Table 'database.active_admin_comments' doesn't exist: SHOW FULL FIELDS FROM `active_admin_comments`
```

### Suggested fix

Something like:
```ruby
module ActiveAdmin
  class Comment < ActiveRecord::Base

    self.table_name = "#{self.table_name_prefix}active_admin_comments"
[...]
```

I'll see if this work tomorrow and if yes I'll create a pull request.

PS: Note same thing is happening for the suffix.

### PR DESCRIPTION
**Pull request by Techbrunch**
Fixes #5093

### CODE REVIEW

**Comment by javierjulio** [comment]
This appears to be right as testing the following in a Rails console does show that setting `table_name` explicitly ignores the prefix and suffix. We have to provide it for it to work.

```sh
>> ActiveRecord::Base.table_name_prefix = 'prefix_'
=> "prefix_"
>> User.table_name
=> "prefix_users"

>> User.table_name= "usersss"
=> "usersss"

>> User.table_name
=> "usersss"
```

**Comment by Fivell** [comment]
@Techbrunch please drop a line to changelog

**Comment by Techbrunch** [comment]
@Fivell Done

**Comment by javierjulio** [comment]
@Techbrunch thanks for the fix! 👏🏻❤️

**Pull request merged**
