### PR TITLE
feat(Column): Add support for formatting date column

### PR DESCRIPTION
**Pull request by emilioeduardob**
This PR allows for passing a format or using the global date/time
format. I'm not sure whether to call the options `format` or `date_format`

### CODE REVIEW

**Comment by timoschilling** [comment]
There is already the `block` for format the value.

I don't like this PR, @seanlinsley what do you think?

**Comment by seanlinsley** [comment]
I think this would make sense. It would be similar to allowing `status_tag: true` to be passed, which I've considered in the past, but never added.

This does need to be rebased because of #4346.

Please also update the documentation with this new feature.

**Comment by seanlinsley** [comment]
@emilioeduardob: ping

**Comment by emilioeduardob** [comment]
Hey! great, I'll rebase and will add documentation for this

**Comment by emilioeduardob** [comment]
How about now @seanlinsley :) ?

**Comment by javierjulio** [comment]
Closing out as its also gotten stale. With @timoschilling on this one. I don't think this is a good change because at the end of the day the block feature solves this and any other customization, for example, timezones. If we were to provide format here and use a block, users could expect both to work as well. I think we ultimately solve the issue at hand.

**Pull request closed without merging**
