### PR TITLE
Allow :remote option to flow to Kaminari

### PR DESCRIPTION
**Pull request by jshow**
https://github.com/activeadmin/activeadmin/issues/5669

```
posts = member.posts.includes(:replies)

paginated_collection(posts.page(params[:page]).per(10), remote: true, params: {controller: 'admin/members', action: 'my_posts'}, download_links: false) do
  table_for(collection, :class => 'index_table') do
        column 'ID', :id

        column 'Title', :title do |post|
          link_to(post.title, "/admin/posts/#{post.id}")
        end
  end
end
```

### CODE REVIEW

**Comment by jshow** [comment]
:remote will require JS and a controller that responds to jasper

Jodi

**Comment by deivid-rodriguez** [comment]
Can you clarify @jshow? What is jasper?

**Comment by jshow** [comment]
> Can you clarify @jshow? What is jasper?

sorry, that was an autocorrect - just back from vacation, I'll provide some supporting code that could make it into docs

**Comment by jshow** [comment]
I've added some documentation that hopefully clears up how to use Kaminari to paginate a table using ajax

@deivid-rodriguez , please let know if this answers your questions

**Comment by deivid-rodriguez** [comment]
I think you need to fix the change set first? It's showing 2,084 additions and 1,219 deletions right now.

**Comment by jshow** [comment]
pulled when I should have rebased

new cherry-picked PR is here: https://github.com/activeadmin/activeadmin/pull/5792

**Pull request closed without merging**
