### PR TITLE
783: Update ActiveAdmin::DatabaseHitDuringLoad error message to offer…

### PR DESCRIPTION
**Pull request by taranda**
… more solutions.

### CODE REVIEW

**Comment by taranda** [comment]
This PR will make the DatabaseHitDuringLoad error  message offer some more solutions which I think will prove useful for many users.

**Comment by taranda** [comment]
When I first encountered this error and the recommendation was to add wrap the query in a proc, I did not immediately know what to do with that.  It took quite a bit of Googling and reviewing issues to finally figure out the solution.  I thought it would be nice to provide a more explicit solution to other developers who encounter this error.

**Comment by varyonic** [comment]
Aha. Improvements to the documentation on how to use procs for filters, an example in demo.activeadmin.info and/or a wiki entry or link to a blog post would all be very welcome.  Maybe even a link to such docs in the error message.

**Comment by deivid-rodriguez** [comment]
I'm not sure this is a good thing to do, so I'd rather not recommend this. Totally :+1: on improving the docs on how to defer query executions by wrapping them in a proc, though. Feel free to submit another PR for that @taranda! I'm going to close this PR for now, but feel free to continue the discussion!

**Pull request closed without merging**
