### PR TITLE
Backport changelog fixes

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
The stable changelog was also full with missing (and some broken) links. This PR backports #5474 and fixes all the issues found by the changelog specs.

### CODE REVIEW

**Comment by varyonic** [comment]
Let's leave this PR open for further changes until 1.4 is ready to ship.

**Comment by deivid-rodriguez** [comment]
Ok, sounds like a good idea to me.

**Comment by deivid-rodriguez** [comment]
I think I misunderstood @varyonic's suggestion. I think he meant that we would push backported commits to this branch instead of opening a PR for each of them. And them merge them all together when we decide to release. I understood the we would log all the changes that will appear in 1.4 in this PR. Now I noticed that what I understood does not make much sense since user facing PRs usually come with their own changelog entries.

Anyways, in principle it sounds better to me to split related backports together instead of having a single jumbo backport PR, but I don't have a strong opinion, and I'm not even sure if that's what @varyonic meant. So I'm going to keep opening separated PRs, and merge this one if approved unless anybody has a different opinion!

**Comment by deivid-rodriguez** [comment]
Ok, merging in then!

**Pull request merged**
