### PR TITLE
Fix #4424, issue with new_with_cast from 6488d63

### LINKED ISSUE #4424: new_with_cast no longer works (regression)
I have a model that uses new_with_cast (an example would be something like http://www.simple10.com/rails-3-sti/ , Option 1)

After commit 6488d6319187c1f0b1f9916cd36d76b84e40f641 , it is no longer working

### PR DESCRIPTION
**Pull request by shaicoleman**

### CODE REVIEW

**Comment by timoschilling** [comment]
Do you want to continue the work on this PR?

**Comment by shaicoleman** [comment]
I've rebased the pull request from the latest master branch

**Comment by Fivell** [comment]
@shaicoleman , would be great to have test for such situations.

**Comment by timoschilling** [comment]
I have reverted this PR

**Pull request merged**
