### PR TITLE
Drop rails 6.0 support

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
It only receives severe security fixes, like 5.2: https://guides.rubyonrails.org/maintenance_policy.html.

Time to drop support!

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
(Took the chance to update a bunch of other stuff in CI).

**Review by javierjulio — APPROVED** [review]
Thanks!

**Comment by rylanb** [comment]
Are you still supporting Rails 6.1? Just wanted to check on that as I wasn't sure

**Comment by deivid-rodriguez** [comment]
Yes.

In general, whatever combination of stable releases of ActiveAdmin and Rails that Bundler allows to be installed together can be considered supported.

**Comment by rylanb** [comment]
Awesome thanks so much! I just wanted to make sure there. 

Thanks for all your hard work and the quick reply!

**Pull request merged**
