### PR TITLE
trigger separate js event for each batch action

### PR DESCRIPTION
**Pull request by Fivell**
before for handling stuff for particular  batch action popup I need to check title 

```js
    $("body.users.index").on("modal_dialog:after_open", function (event, form) {
        if (form.parent().find('.ui-dialog-titlebar .ui-dialog-title').text() === 'Send Email') {
         //... my code 
        }
        if (form.parent().find('.ui-dialog-titlebar .ui-dialog-title').text() === 'Block Users') {
         //... my code 
        }
   }
```

Idea is give such opportunity

```js
    $("body.users.index").on("modal_dialog:send_email:after_open", function (event, form) {
         //... my code 
    }

   $("body.users.index").on("modal_dialog:block_users:after_open", function (event, form) {
         //... my code 
    }
```

### CODE REVIEW

**Comment by Fivell** [comment]
@activeadmin/collaborators  what do you think ?

**Comment by deivid-rodriguez** [comment]
Looks pretty neat to me. I have never used this myself nor tried this PR but I trust you :)

It'd be nice to fix our jasmine tests (#3363) so we can easily test these things...

Needs a change log entry as a new feature for 1.1.0!

**Comment by Fivell** [comment]
@deivid-rodriguez  I will re-check everything manually and add change-log after will be sure, 
adding WIP again

**Comment by Fivell** [comment]
@deivid-rodriguez , works

```
$(document).ready(function(){
    $( "body" ).on( "modal_dialog:after_open", function( event, param ) {
      console.log(event); console.log(param);
    });

    $( "body" ).on( "modal_dialog:before_open", function( event, param ) {
        console.log(event); console.log(param);
    });

    $( "body" ).on( "modal_dialog:destroy:after_open", function( event, param ) {
        console.log(event); console.log(param);
    });

    $( "body" ).on( "modal_dialog:destroy:before_open", function( event, param ) {
        console.log(event); console.log(param);
    });
});

```
image

**Pull request merged**
