### PR TITLE
Updated patch and gem version

### PR DESCRIPTION
**Pull request by ferdinandrosario**

### CODE REVIEW

**Comment by timoschilling** [comment]
why should we only allow `1.7.x`?

**Comment by ferdinandrosario** [comment]
not necessary, If you wish I will revert that. just wanted to ensure user are using the latest version ..
Shall I remove it 1.7.x?

**Comment by timoschilling** [comment]
It is not our task to ensure that the user use the latest versions. We only say we need `> 1.3` while `1.2` has a bug or while we need a feature that is introduced in `1.3`. So, yes please revert that.

**Comment by ferdinandrosario** [comment]
Done :+1:

**Pull request merged**
