### PR TITLE
Add a minimal git history to generated test apps

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
It's very common to make experimental modifications to test applications. This makes it very easy to go back to the freshly generated application without having to regenerate it, by running `git checkout .`, or to even keep track of the experimental changes being done using git.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
Nothing really changes regarding our testing instructions. The only difference is that if developers navigate to the generated application they will see

```
$ git status
On branch master
nothing to commit, working tree clean

$ git log
commit 49ed0838e18ef5e7893fea1a5f98a2e707fa66fe (HEAD -> master)
Author: David Rodríguez <deivid.rodriguez@riseup.net>
Date:   Thu Jun 13 11:49:41 2019 +0200

    Bare application with data

commit 0abea712b22adbbcba72253c12aa90ed253befe5
Author: David Rodríguez <deivid.rodriguez@riseup.net>
Date:   Thu Jun 13 11:48:58 2019 +0200

    Bare application
```

instead of something like

```
$ git status
On branch master

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	.gitignore
	.ruby-version
	README.md
	Rakefile
	app/
	bin/
	config.ru
	config/
	db/
	lib/
	log/
	package.json
	public/
	spec/
	storage/
	test/
	tmp/
	vendor/

nothing added to commit but untracked files present (use "git add" to track)
```

**Comment by javierjulio** [comment]
Ah so the generated application is treated as a separate git repo with its own commits? I wasn’t sure if that was the case.

**Comment by deivid-rodriguez** [comment]
Yeah. Well, that was already the case since rails generators automatically run `git init` unless you pass `--skip-git`. But everything was left uncommitted prior to this PR.

Now we add some initial commits, so any edits made by developers will be more apparent and it will be easier to discard them and go back to the fresh version of the application.

**Comment by javierjulio** [comment]
Sounds good thanks! I’m not at my Mac so I wasn’t able to try it. I’ll do that soon. Thanks again!

**Pull request merged**
