### PR TITLE
Use filter label when condition has a predicate

### PR DESCRIPTION
**Pull request by ko-lem**
This resolves issue [5885](https://github.com/activeadmin/activeadmin/issues/5885).

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
Nice! Thanks for fixing this!

Can you add a changelog entry under "Unrelased > Bug Fixes", following the existing changelog format?

**Comment by ko-lem** [comment]
Sure

**Comment by javierjulio** [comment]
Thank you! 🙌🏻

**Comment by ko-lem** [comment]
:)

**Review by johnaAr555 — APPROVED** [review]

**Pull request merged**
