### PR TITLE
Revert "Ensure application gets reloaded only once"

### LINKED ISSUE #5787: reloading much slower after 2.1 upgrade in development mode for a larger code base and about 25 active admin entities
### Expected behavior

We were hoping the release 2 would bring some reload performance improvements in development mode.

### Actual behavior

Reload performance (after touching some class in development mode) has become extremely slow. Strange enough enough, initial load is still about the same speed. 

## Context

- rails 5.2.x
- ruby 2.6.x
- tested on 2 mac's : i5 / 16gb ram

## analysis

from the logs it seems that active admin now somehow triggers a multitude of the same class reloads, below just an extract of one request log that appears to trigger class reloading of the same classes multiple times (and the amount of times seems to be increasing per request)

```
/Users/koen/Personal/allcrux/app/admin/customer.rb:66: warning: already initialized constant BOOTSWATCH_V3
/Users/koen/Personal/allcrux/app/admin/customer.rb:66: warning: previous definition of BOOTSWATCH_V3 was here
/Users/koen/Personal/allcrux/app/admin/user.rb:7: warning: already initialized constant RANKDIR
/Users/koen/Personal/allcrux/app/admin/user.rb:7: warning: previous definition of RANKDIR was here
/Users/koen/Personal/allcrux/app/admin/customer.rb:66: warning: already initialized constant BOOTSWATCH_V3
/Users/koen/Personal/allcrux/app/admin/customer.rb:66: warning: previous definition of BOOTSWATCH_V3 was here
/Users/koen/Personal/allcrux/app/admin/user.rb:7: warning: already initialized constant RANKDIR
/Users/koen/Personal/allcrux/app/admin/user.rb:7: warning: previous definition of RANKDIR was here
/Users/koen/Personal/allcrux/app/admin/customer.rb:66: warning: already initialized constant BOOTSWATCH_V3
/Users/koen/Personal/allcrux/app/admin/customer.rb:66: warning: previous definition of BOOTSWATCH_V3 was here
/Users/koen/Personal/allcrux/app/admin/user.rb:7: warning: already initialized constant RANKDIR
/Users/koen/Personal/allcrux/app/admin/user.rb:7: warning: previous definition of RANKDIR was here
/Users/koen/Personal/allcrux/app/admin/customer.rb:66: warning: already initialized constant BOOTSWATCH_V3
/Users/koen/Personal/allcrux/app/admin/customer.rb:66: warning: previous definition of BOOTSWATCH_V3 was here
/Users/koen/Personal/allcrux/app/admin/user.rb:7: warning: already initialized constant RANKDIR
/Users/koen/Personal/allcrux/app/admin/user.rb:7: warning: previous definition of RANKDIR was here
/Users/koen/Personal/allcrux/app/admin/customer.rb:66: warning: already initialized constant BOOTSWATCH_V3
/Users/koen/Personal/allcrux/app/admin/customer.rb:66: warning: previous definition of BOOTSWATCH_V3 was here
/Users/koen/Personal/allcrux/app/admin/user.rb:7: warning: already initialized constant RANKDIR
/Users/koen/Personal/allcrux/app/admin/user.rb:7: warning: previous definition of RANKDIR was here
...
```

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
This reverts commit 21b6138fdcf58cd54c3f1d3f60cb1127b174b40f from #5740, because it
created a performance regression in development when reloading code.

Closes #5787.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
Can anyone able to reproduce the performance issue confirm that this change fixes it?

/cc @koenhandekyn @gingerlime @oskarpearson @jscheid

**Comment by gingerlime** [comment]
@deivid-rodriguez I did a quick test with this branch on my dev box and it seemed to have fixed it.

**Comment by koenhandekyn** [comment]
configured the branch and confirming it seems fixed on our application!

**Comment by deivid-rodriguez** [comment]
Great, thanks both for confirming! :heart:

**Pull request merged**
