### PR TITLE
WIP: Use Travis CI's cache instead

### PR DESCRIPTION
**Pull request by dlackty**
**WIP**

Try to simplify & probably speed up build process. 
Now it takes more than 30 minutes to finish a CI build.

### CODE REVIEW

**Comment by timoschilling** [comment]
please take a look in the old not merged PR's, there are 1 or 2 with the same target

**Comment by timoschilling** [comment]
#3640 and #4161

**Comment by dlackty** [comment]
@timoschilling Thanks! I'll take a look on it.

**Comment by dlackty** [comment]
Closed in favor of #4510

**Pull request closed without merging**
