### PR TITLE
Drop Rails < 4.2 support

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
The idea here is to get in sync with Rails regarding supported versions before releasing 1.0.0. @timoschilling hasn't yet agreed (or disagreed) with this, but I thought I would give it a try! :)

### CODE REVIEW

**Comment by varyonic** [comment]
I don't know when to merge this, but the changes look correct.

**Comment by deivid-rodriguez** [comment]
Sweet, thanks @Fivell, I'll work on that!

**Comment by deivid-rodriguez** [comment]
Isn't that one fixed here?

**Comment by deivid-rodriguez** [comment]
@Fivell I added one more simplification, but I think conditional handling of `to_unsafe_h` is still needed, since I think it's a Rails 5 only thing.

**Comment by Fivell** [comment]
@deivid-rodriguez , http://apidock.com/rails/v4.2.1/ActionController/Parameters/to_unsafe_h what about this one ?

**Comment by deivid-rodriguez** [comment]
Right.

Feel free to add commits to this branch since you have already studied how this works in the different versions.

**Comment by Fivell** [comment]
@deivid-rodriguez ,  ok but a little later

**Comment by deivid-rodriguez** [comment]
:+1: Thanks!

**Comment by Fivell** [comment]
@deivid-rodriguez , now I think your turn to review

**Comment by deivid-rodriguez** [comment]
@Fivell :+1: Sorry I didn't get to review this. Still busy...

**Pull request merged**
