### PR TITLE
362 right to left layout

### PR DESCRIPTION
**Pull request by eshaiju**
Added right to left layout option by adding

```
 <html lang="<%=I18n.locale%>" >
```

 Also added rtl.scss for switching styles.
Now we need to add documention which instruct user to add 

```
html[lang=ar] {
  @import "active_admin/rtl.scss";
}
```

### CODE REVIEW

**Comment by timoschilling** [comment]
There are some layout problems in the RTL state:

1. The breadcrumbs are on the right side, but still in LTR order
2. The index table is not resigning in RTL, but is resigning in LTR

**Comment by eshaiju** [comment]
Hi @timoschilling 

Didint understood the 2 nd problem

**Comment by timoschilling** [comment]
The EN images are ok, AR are wrong

With a big browser window:



With a small window:

**Comment by eshaiju** [comment]
Hi @timoschilling  

I will rework on all RTL CSS with my designer friend @imran04u and push with in a week

**Comment by timoschilling** [comment]
any updates?

**Comment by maysam** [comment]
any updates?

**Comment by amit0001** [comment]
Any updates?

**Comment by javierjulio** [comment]
Going to close out as stale. We can track working on a new updated solution in the issue #362. I think it would be great to support RTL languages in AA and with v2 it will hopefully be easier with the CSS overhaul I'm doing in #3862. I'm thinking RTL support could be a great candidate for a v2.1 release perhaps.

**Pull request closed without merging**
