### PR TITLE
Rework development mode code reloading

### PR DESCRIPTION
**Pull request by chancancode**
This commit improved the code reloading mechanisms in a few ways:

1. Avoid reloading the routes unless the admin files has changed
2. Avoid reloading the routes twice in the same request if they were already
   reloaded by Rails
3. Respect the `reload_classes_only_on_change` config

In a big application with lots of routes, reloading them would be very costly, so it's something that should be avoided if possible.

### CODE REVIEW

**Comment by chancancode** [comment]
before

after

**Comment by seanlinsley** [comment]
Thanks so much for working to improve reloading performance!

In your big application, how long did initial load take before, and how much has this shaved off?

**Comment by chancancode** [comment]
Before (baseline – no files changed, so nothing is reloaded):

before-baseline

Before (routes changed – `touch config/routes.rb`)

before-routes-changed

After (baseline – no files changed, so nothing is reloaded):

after-baseline

After (routes changed – `touch config/routes.rb`)

after-routes-changed

For our purpose, we are only interested in the page generation time (which is approximated by the TTFB/time-to-first-byte). So I think we are looking at a ~30% improvement here.

**Comment by chancancode** [comment]
(The build failure seems unrelated, it appears to be failing for the same reason as the latest commit on master)

**Comment by timoschilling** [comment]
Good work!!!

I can confirm that there are failing test, before your change, see #3781. I hope some can fix that before we merge this, to get the cucumber tests running.

I hope, I or @seanlinsley or some else find some time to test it locale.

**Comment by timoschilling** [comment]
please rebase this commit, #3781 is closed

**Comment by chancancode** [comment]
Rebased!

**Comment by timoschilling** [comment]
@chancancode thanks for the good work :+1: 
Maybe you can take a look onto #697 and help us there too.

**Pull request merged**
