### PR TITLE
Fix routes deprecation warning for Rails 8.x

### PR DESCRIPTION
**Pull request by tagliala**
Close: #8498

Ref: rails/rails#52422

### CODE REVIEW

**Comment by tagliala** [comment]
Trying to understand how I had this deprecation message on my dev machine, does not seem to affect 8.0.0.beta1

**Comment by tagliala** [comment]
Sorry, I can't replicate the deprecation but this commit should not hurt

**Comment by javierjulio** [comment]
@tagliala the reason is this was actually reverted in https://github.com/rails/rails/commit/5c0b7496ab32c25c80f6d1bdc8b32ec6f75ce1e4 as I noticed from [this rubocop-rails PR comment](https://github.com/rubocop/rubocop-rails/pull/1329#issuecomment-2322661505).

**Comment by tagliala** [comment]
Thanks for noticing. I didn't see the revert PR linked to the PR I was taking a look to.

What should we do?

**Comment by javierjulio** [comment]
@tagliala the reason nothing was linked is that there was no PR. It was a revert commit that was pushed directly to the default branch. Hmm well it doesn't seem worth doing the change because there is no deprecation now. Reviewing other PR's following that, [there was another revert as well](https://github.com/rails/rails/pull/52664). Rails is making changes to routing but seems to be scaled back a bit. I think we should ignore this for now and only make a change once we have deprecations from an official release. Thank you.

**Pull request closed without merging**
