### PR TITLE
Opt-in for MFA requirement

### PR DESCRIPTION
**Pull request by tagliala**
Make the gem more secure by requiring that all privileged operations by any of the owners require OTP.

Ref: https://guides.rubygems.org/mfa-requirement-opt-in/

### CODE REVIEW

**Review by javierjulio — APPROVED** [review]
@tagliala thank you! Please check your Twitter DM. 😁

**Comment by javierjulio** [comment]
@tagliala if you're interested we could use the same update in both Arbre and Inherited Resources repositories and I would accept the PR.

**Comment by tagliala** [comment]
Done, I had both of them already forked for the update to Rails 7

**Comment by javierjulio** [comment]
@tagliala thank you! We appreciate all your help. Would you be interested in joining the ActiveAdmin team? I've sent you a Twitter DM with more details.

**Pull request merged**
