### PR TITLE
Two-column layout to better utilize screen space

### PR DESCRIPTION
**Pull request by colorfulfool**
A small change to forms layout to better utilize the limited screen space of our laptops. I'm using a MacBook Air as my main computer, I'm sure many of you do too.

Note the difference in vertical space for the same form:

compare

Main fieldsets are laid out in two columns, nested forms — in however many fit on screen. (I guess, this functionality should be an optional and disabled by default but I don't know a good way to achieve that, is there one?)

### CODE REVIEW

**Comment by varyonic** [comment]
Thanks Anton.  It doesn't work everywhere, but have you tried Arbre columns in your forms? e.g. #4043

**Comment by colorfulfool** [comment]
I thought about `columns do`, of course. But that implies the need to go in and "design" every form. I.e. specify not only semantic blocks (`inputs do`) but also looks.

The value of an administrative framework is in not having to do that. You can drop in your models and get a reasonably good interface. If you want to "design" your pages, you will go for a fully custom solution, you're not an ActiveAdmin customer anymore.

**Comment by deivid-rodriguez** [comment]
I would delegate this decision to @javierjulio, but it definitely does not belong in 1.0.0.

**Comment by varyonic** [comment]
I'm not convinced to make this change.  I think it could be an unwanted surprise for some existing users.  The current default is easy to override if you don't like it.

**Comment by deivid-rodriguez** [comment]
Me neither.

**Comment by varyonic** [comment]
@colorfulfool Thanks for the suggestion. Use for yourself but we're going to pass on merging this for now.

**Comment by deivid-rodriguez** [comment]
I'd still like @javierjulio's opinion.

**Comment by javierjulio** [comment]
I saw this earlier before it was closed and thought I could get away. 😏 Thanks @deivid-rodriguez. 🙄😂 I do think its a nice addition but I don't think we should be adding anything unless absolutely necessary. This is something that an AA user can add easily (as was shown) so I think its a win. My thinking is we should be more concerned with the core CSS/JS in ActiveAdmin by updating and simplifying it. Having a nice set of variables for others to customize the appearance and then anything else others can write custom CSS for without having to override a lot of our styles with long selectors.

But since this is specific to forms I do have a lot to say about that. I wanted to do a lot more with forms regarding styling but its just brutal. Painful. I really despise the HTML Formtastic spits out. I know why it does it but its just very hard to style without breaking something else because of how the cascade works. Modern frameworks like Bootstrap, Foundation or the many others have solved this with a component based approach. The thing is that we'd also have to modify the Formtastic HTML. I'm not sure we'd want to do that and if we did I saw that being just as much as work as what I did in #3862 if not more so its why I just tried to clean up the styles for forms and not much else.

My thinking remains the same: to simplify and modernize the base CSS in AA so its easy and less painful for users to override because mainly there would be less of it and also not such long selectors to override (one was 3 id's and 1 class, in a single selector! 😳). With many variables thrown in, it becomes pretty easy to configure and anything else would require setting your own CSS in cases like this. But first before we think of doing this we really need to simplify the CSS we have so we can take on bigger projects with it, otherwise you're just applying small and large bandaids.

**Comment by colorfulfool** [comment]
@javierjulio Thanks for such an expanded response, didn't expect that 👍

**Pull request closed without merging**
