### PR TITLE
Require only minimum of sass as dependency

### PR DESCRIPTION
**Pull request by javierjulio**
This should help with issues like #5031 where users want to use sassc-rails but were not able to since we were requiring sass-rails. We could probably still have it as a dependency but simply **not** require it in Ruby code. This change was to mimic what I've seen in other gems for Rails apps that include SASS like [foundation-rails where they specify the minimum dependencies](https://github.com/zurb/foundation-rails/blob/master/foundation-rails.gemspec#L21-L23) rather than require sass-rails directly.

### CODE REVIEW

**Comment by javierjulio** [comment]
@deivid-rodriguez another codecov/project failure. Is it ok to ignore?

**Comment by Fivell** [comment]
@javierjulio , maybe this worth change-log line

**Comment by deivid-rodriguez** [comment]
@javierjulio The codecov/project failure is fine, yes!

The changes here look good to me, let's wait for @swrobel's feedback!

**Comment by swrobel** [comment]
Seems to be working great on my staging server! 👍

**Comment by deivid-rodriguez** [comment]
Nice! @javierjulio `sass-rails` depends on `sass ~> 3.1`, should we add that here too, just in case?

**Pull request merged**
