### PR TITLE
Make it possible to use dynamic names for scopes.

### PR DESCRIPTION
**Pull request by nashby**
Right now it's possible to pass a proc but it's evaluated outside
of view context so it's not possible to use helper methods and stuff.

### CODE REVIEW

**Comment by timoschilling** [comment]
Whats you real world usecase for this?

**Comment by nashby** [comment]
@timoschilling hey! Use-case is pretty straightforward: I need to create scopes with name tied to the `current_user` or `current_organization` object (view helpers). Right now it's not possible to use methods from view context.

**Comment by deivid-rodriguez** [comment]
Isn't this actually documented? https://github.com/activeadmin/activeadmin/blob/master/docs/3-index-pages.md#index-scopes. If that's the case, I'd say this is a bug fix! :)

**Comment by nashby** [comment]
@deivid-rodriguez yeah, it's kinda bug fix actually. :)

**Comment by timoschilling** [comment]
Please rebase your PR, then we can merge

**Comment by nashby** [comment]
@timoschilling done!

**Comment by timoschilling** [comment]
@nashby can you take a look on the specs

**Comment by nashby** [comment]
@timoschilling should be fixed now.

**Comment by Fivell** [comment]
@nashby please rebase

**Comment by nashby** [comment]
done

**Pull request merged**
