### PR TITLE
#2753 - status_tag supports boolean status (fix)

### PR DESCRIPTION
**Pull request by vanekjar**
Hi guys,

I fixed this issue little bit. Previous version didn't worked for me. It had been accepting only boolean value in a string which I think made no sense.

### CODE REVIEW

**Comment by timoschilling** [comment]
@vanekjar do you still wont to work on this?

**Comment by vanekjar** [comment]
Actually not, I just made that simple hot fix. Web frontend is not my cup of tee. So I better pass it to someone else.

**Comment by javierjulio** [comment]
@timoschilling for Enum support I took a peak and you should be able to do this but I'm having trouble updating my test-rails-app to 4.2.1 for testing (my original setup is rails 3.2). I'd switch but I need to maintain my test app as I have several changes to test out UI/CSS changes.

In components/table_for#render_data

```ruby
value = status_tag value     if is_boolean?(data, item) || item.class.defined_enums.has_key?(data)
```

The examples you gave using "name" are rather confusing. I'd just keep the component super simple with just the first argument and leave it at that.

In my WIP CSS branch I've added the FALSE_VALUES list (added nil to the array to preserve backwards compatibility).

**Comment by timoschilling** [comment]
@javierjulio I have changed my example. `scope` should be better then `name`. For your test app problem I have 2 solutions:

**The official way**
use `script/use_rails` to switch the rails version, see [CONTRIBUTING#5-view-your-changes-in-a-rails-application](https://github.com/activeadmin/activeadmin/blob/master/CONTRIBUTING.md#5-view-your-changes-in-a-rails-application) for details

**The better way**
1. `script/use-rails 3.2.21`
2. `script/local server`
3. `script/use-rails 4.2.1`
4. `script/local server`
5. `cp -r .test-rails-apps ../activeadmin-test-apps`
6. copy the ActiveAdmin Gemfiles to each of the test apps
7. edit the Gemfiles
  1. remove line https://github.com/activeadmin/activeadmin/blob/master/Gemfile#L3-L8
  2. add this lines
```ruby
gem 'activeadmin', path: '../../activeadmin'
gem 'rails', 'YOUR_RAILS_VERSION'
```

**Comment by seanlinsley** [comment]
Closing as stale

**Pull request closed without merging**
