### PR TITLE
Fix Cucumber specs for Devise

### PR DESCRIPTION
**Pull request by merqlove**
Subj. 
Seems `devise` and `arbre` is updated.

### CODE REVIEW

**Comment by timoschilling** [comment]
Can you please provide a separate PR for the arbre fix, I want to merge that.

The devise fix can break with the next devise version. We should go a other way there.
We should inject our own text into the devise translation or we should read the devise translations and match against that. Then we are safe for future changes in devise.

**Comment by merqlove** [comment]
Ok

**Comment by merqlove** [comment]
Hi, it is. Prepared for locales.

**Comment by timoschilling** [comment]
👍 just waiting for travis

**Pull request merged**
