### PR TITLE
Resolve dart sass deprecation warning for division

### LINKED ISSUE #7064: Deprecation warning on / for division in forms.scss
### Did you find a bug?

After switching to a SCSS preprocessor that uses Dart Sass, we started seeing the following deprecation warning:

```sh
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.
 
 Recommendation: math.div($sidebar-inner-content-width, 2)
 
 More info and automated migrator: https://sass-lang.com/d/slash-div
 
     ╷
 279 │ $side-by-side-filter-input-width: ($sidebar-inner-content-width / 2) - ($text-input-horizontal-padding * 2) - $filter-field-seperator-width;
     │                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     ╵
     node_modules/@activeadmin/activeadmin/src/scss/_forms.scss 279:36  @import
     node_modules/@activeadmin/activeadmin/src/scss/_base.scss 8:9      @import
     app/packs/stylesheets/active_admin.scss 12:9                       root stylesheet
 
 Recommendation: math.div($sidebar-inner-content-width, 2)
 
     ╷
 280 │ $side-by-side-filter-select-width: ($sidebar-inner-content-width / 2) - $filter-field-seperator-width;
     │                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     ╵
     node_modules/@activeadmin/activeadmin/src/scss/_forms.scss 280:37  @import
     node_modules/@activeadmin/activeadmin/src/scss/_base.scss 8:9      @import
     app/packs/stylesheets/active_admin.scss 12:9                       root stylesheet
 
 Recommendation: math.div($sidebar-inner-content-width, 2)
 
     ╷
 282 │ $date-range-filter-input-width: ($sidebar-inner-content-width / 2) - ($filter-field-seperator-width / 2);
     │                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     ╵
     node_modules/@activeadmin/activeadmin/src/scss/_forms.scss 282:34  @import
     node_modules/@activeadmin/activeadmin/src/scss/_base.scss 8:9      @import
     app/packs/stylesheets/active_admin.scss 12:9                       root stylesheet
 
 Recommendation: math.div($filter-field-seperator-width, 2)
 
     ╷
 282 │ $date-range-filter-input-width: ($sidebar-inner-content-width / 2) - ($filter-field-seperator-width / 2);
     │                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     ╵
     node_modules/@activeadmin/activeadmin/src/scss/_forms.scss 282:71  @import
     node_modules/@activeadmin/activeadmin/src/scss/_base.scss 8:9      @import
     app/packs/stylesheets/active_admin.scss 12:9                       root stylesheet
```

### Expected behavior

There should be no deprecation warnings.

### Actual behavior

What actually happens?

### How to reproduce

We are using `rails/webpacker` 6.0beta7, with `sass` 1.35.1 in a webpack configuration for our Rails app.

Note: this change isn't yet released to `libsass` or `rubysass` according to the [Sass site](https://sass-lang.com/documentation/breaking-changes/slash-div), and it was not clear to me what the standard Rails installations use for Sprockets or Webpack (I believe for Webpack it uses dart-sass).

### PR DESCRIPTION
**Pull request by tordans**
Closes #7064

Dart sass has deprecated using `$value / $value` for division and introduced `math.div($value, $value)` as an alternative. It shows deprecation warnings like …

```
hot.1  | 282 │ $date-range-filter-input-width: ($sidebar-inner-content-width / 2) - ($filter-field-seperator-width / 2);
hot.1  |     │                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
hot.1  |     ╵
hot.1  |     node_modules/@activeadmin/activeadmin/src/scss/_forms.scss 282:34  @import
hot.1  |     node_modules/@activeadmin/activeadmin/src/scss/_base.scss 8:9      @import
hot.1  |     app/javascript/stylesheets/active_admin.sass 14:9                  root stylesheet
hot.1  |
hot.1  | DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.
hot.1  |
hot.1  | Recommendation: math.div($filter-field-seperator-width, 2)
```

However, https://sass-lang.com/documentation/breaking-changes/slash-div#transition-period shows, that LibSass and RubySass did not transition yet.

To work around using `math.div`, https://blog.getbootstrap.com/2021/06/22/bootstrap-5-0-2/#sass-division recommends replacing division with multiplication – which is what this PR does.

### CODE REVIEW

**Comment by gingerlime** [comment]
Any chance to get this merged? seems like a safe change.

**Comment by nordhagen** [comment]
Really looking forward to not having this flood my terminal with every hot rebuild. Please merge!

```
13:50:06 webpacker.1 | Recommendation: math.div($sidebar-inner-content-width, 2)
13:50:06 webpacker.1 | 
13:50:06 webpacker.1 | More info and automated migrator: https://sass-lang.com/d/slash-div
13:50:06 webpacker.1 | 
13:50:06 webpacker.1 |     ╷
13:50:06 webpacker.1 | 279 │ $side-by-side-filter-input-width: ($sidebar-inner-content-width / 2) - ($text-input-horizontal-padding * 2) - $filter-field-seperator-width;
13:50:06 webpacker.1 |     │                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
13:50:06 webpacker.1 |     ╵
13:50:06 webpacker.1 |     node_modules/@activeadmin/activeadmin/src/scss/_forms.scss 279:36  @import
13:50:06 webpacker.1 |     node_modules/@activeadmin/activeadmin/src/scss/_base.scss 8:9      @import
13:50:06 webpacker.1 |     app/javascript/stylesheets/active_admin.scss 13:9                  root stylesheet
13:50:06 webpacker.1 | 
13:50:06 webpacker.1 | DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.
13:50:06 webpacker.1 | 
13:50:06 webpacker.1 | Recommendation: math.div($sidebar-inner-content-width, 2)
13:50:06 webpacker.1 | 
13:50:06 webpacker.1 | More info and automated migrator: https://sass-lang.com/d/slash-div
13:50:06 webpacker.1 | 
13:50:06 webpacker.1 |     ╷
13:50:06 webpacker.1 | 280 │ $side-by-side-filter-select-width: ($sidebar-inner-content-width / 2) - $filter-field-seperator-width;
13:50:06 webpacker.1 |     │                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
13:50:06 webpacker.1 |     ╵
13:50:06 webpacker.1 |     node_modules/@activeadmin/activeadmin/src/scss/_forms.scss 280:37  @import
13:50:06 webpacker.1 |     node_modules/@activeadmin/activeadmin/src/scss/_base.scss 8:9      @import
13:50:06 webpacker.1 |     app/javascript/stylesheets/active_admin.scss 13:9                  root stylesheet
13:50:06 webpacker.1 | 
13:50:06 webpacker.1 | DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.
13:50:06 webpacker.1 | 
13:50:06 webpacker.1 | Recommendation: math.div($sidebar-inner-content-width, 2)
13:50:06 webpacker.1 | 
13:50:06 webpacker.1 | More info and automated migrator: https://sass-lang.com/d/slash-div
13:50:06 webpacker.1 | 
13:50:06 webpacker.1 |     ╷
13:50:06 webpacker.1 | 282 │ $date-range-filter-input-width: ($sidebar-inner-content-width / 2) - ($filter-field-seperator-width / 2);
13:50:06 webpacker.1 |     │                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
13:50:06 webpacker.1 |     ╵
13:50:06 webpacker.1 |     node_modules/@activeadmin/activeadmin/src/scss/_forms.scss 282:34  @import
13:50:06 webpacker.1 |     node_modules/@activeadmin/activeadmin/src/scss/_base.scss 8:9      @import
13:50:06 webpacker.1 |     app/javascript/stylesheets/active_admin.scss 13:9                  root stylesheet
13:50:06 webpacker.1 | 
13:50:06 webpacker.1 | DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.
13:50:06 webpacker.1 | 
13:50:06 webpacker.1 | Recommendation: math.div($filter-field-seperator-width, 2)
13:50:06 webpacker.1 | 
13:50:06 webpacker.1 | More info and automated migrator: https://sass-lang.com/d/slash-div
13:50:06 webpacker.1 | 
13:50:06 webpacker.1 |     ╷
13:50:06 webpacker.1 | 282 │ $date-range-filter-input-width: ($sidebar-inner-content-width / 2) - ($filter-field-seperator-width / 2);
13:50:06 webpacker.1 |     │                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
13:50:06 webpacker.1 |     ╵
13:50:06 webpacker.1 |     node_modules/@activeadmin/activeadmin/src/scss/_forms.scss 282:71  @import
13:50:06 webpacker.1 |     node_modules/@activeadmin/activeadmin/src/scss/_base.scss 8:9      @import
13:50:06 webpacker.1 |     app/javascript/stylesheets/active_admin.scss 13:9                  root stylesheet
```

**Comment by joker-777** [comment]
Guys, it would be great if you could merge this!

**Comment by clinejj** [comment]
@javierjulio possible to get a review on this?

**Review by varyonic — APPROVED** [review]

**Comment by alejandroperea** [comment]
I have the same problem here. It will be nice if this can be merged and do a new release 🙇‍♂️

**Comment by jaynetics** [comment]
@varyonic could you merge this?

**Review by Fivell — APPROVED** [review]

**Comment by ashrocket** [comment]
@tordans  any ideas why this didn't complete?

**Comment by nordhagen** [comment]
Please, please merge this 🙏

**Review by deivid-rodriguez — APPROVED** [review]
👍

**Comment by deivid-rodriguez** [comment]
Not sure why the coverage checks didn't work, but I ignored that issue for now.

**Comment by gingerlime** [comment]
Any chance of releasing a new version of activeadmin with this fix?

**Comment by deivid-rodriguez** [comment]
I'm still trying to catch up with everything, but I'll make a release as soon as possible.

**Comment by gingerlime** [comment]
Thank you @deivid-rodriguez ! we really appreciate your work on active admin. I know it can be time consuming and not particularly rewarding at times, but your work is definitely appreciated and recognized.

**Pull request merged**
