### PR TITLE
Relax kaminari dependency for kaminari 1.0.0

### PR DESCRIPTION
**Pull request by sue445**
kaminari v1.0.0 is released!

* https://rubygems.org/gems/kaminari/versions/1.0.0
* https://github.com/kaminari/kaminari/blob/master/CHANGELOG.md#100

It seems no problem at my environment. (Ruby 2.4.0, Rails 5.0.1)

### CODE REVIEW

**Comment by timoschilling** [comment]
The tests are not working with ruby 1.9, while Kaminari 1.0 no longer supports RUby <2.0

We can merge this if https://github.com/kaminari/kaminari/pull/847 is merged and released

**Comment by sue445** [comment]
🙇

**Comment by timoschilling** [comment]
one other option is that we can set different kaminari versions in our `Gemfile` for Ruby 1.9 and >2

**Comment by sue445** [comment]
hmm...

I fixed that use kaminari 0.x when travis uses ruby 1.9.
5dca341

**Comment by varyonic** [comment]
Does this resolve #4173 ?

**Comment by sue445** [comment]
No. This problem is not solved.

image

**Pull request merged**
