### PR TITLE
Add xdan-datetimepicker-rails and datetime_picker input

### PR DESCRIPTION
**Pull request by shekibobo**
Adds [XDSoft's DateTime picker](http://xdsoft.net/jqplugins/datetimepicker/) as the `combined_date_time_picker` input for forms.

[IRC](https://botbot.me/freenode/activeadmin/msg/12028495/) prompting this PR.

Please try this out and see if there's any tweaks or suggestions to better implement this, or if you notice any bugs.

### CODE REVIEW

**Comment by Fivell** [comment]
@shekibobo , do you need any help ?  This feature is very cool, hope it will be merged soon

**Comment by shekibobo** [comment]
hey, sorry for falling off the planet for a while. I haven't really been working in ActiveAdmin for a few months now (actually working in Android these days), so I haven't really had a lot of time to focus on this.

I have been seeing more activity on the timepicker lately, and I've been meaning to look into it to see if new work would mean easier integration. I will try to update my gem repo for xdan-datetimepicker today, but if anyone else would like to take up this torch, I'd really appreciate it, but honestly I'm probably not going to have the free time to work past the challenges for this integration.

That being said, the README for the gem does include some examples on how to integrate the timepicker using both formtastic and simple_form, which I had mostly extracted from this PR and used in my own projects that used AA.

**Comment by Fivell** [comment]
I continue working on this feature here https://github.com/Fivell/activeadmin/tree/timepicker 
 - ```CombinedDateTimePickerInput``` renamed to ```DateTimePickerInput```
 - fixed specs and cucumber features
 - undo deletion of DatePicker while  DateTimePickerInput integration is not completed. 

If somebody want's to play with it you can use this branch or plugin https://github.com/ActiveAdminPlugins/activeadmin_datetimepicker 


Things todo before even thinking to merge to AA

 - restyle datetimepicker using AA styles, respecting sass variables and so on  (this is where I need community help)
 - replace datepicker with date_time_picker (can be customised even for time picker )

**Comment by timoschilling** [comment]
While @Fivell has released a integration as gem, I no longer see a reason for this PR

**Pull request closed without merging**
