### PR TITLE
Test against JRuby and Rubinius

### PR DESCRIPTION
**Pull request by seanlinsley**

### CODE REVIEW

**Comment by kennethkalmer** [comment]
@seanlinsley is there anything we can do to resurrect this effort?

**Comment by timoschilling** [comment]
@kennethkalmer I think @seanlinsley no longer work on this. @dmitry is working on a new rubinius support in #3742. You can help him or create a new new PR to support JRruby

**Comment by timoschilling** [comment]
@kennethkalmer you can pick up commits from @seanlinsley if they helpfull and create a WIP PR like @dmitry does

**Comment by kennethkalmer** [comment]
Just opened #3792 for a wip-style progress report. Actually getting the tests running has been surprisingly easy

**Comment by timoschilling** [comment]
closed while continued in #3792 jRuby and #3742 Rubinius

**Pull request closed without merging**
