### PR TITLE
Fix Hebrew translations

### PR DESCRIPTION
**Pull request by humancopy**

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
My mention-bot config didn't work... :(

Regarding the PR, there's some strings you left untranslated... Any reason?

**Comment by varyonic** [comment]
Thanks.  We are looking for help with #3716 if you know anyone who can.

**Comment by humancopy** [comment]
I've translated the stuff that was missing ... By the way, the link in `unsupported_browser.turn_off_compatibility_view` is outdated. I've updated it in all the translation files and also localised it, though for IE 11 they have a new article at https://support.microsoft.com/en-us/help/17472, so maybe need to reflect it in the translation somehow?

**Comment by javierjulio** [comment]
@humancopy I've updated this on a major update I'm doing for ActiveAdmin in #3862. I'd suggest to use the same language and link from: https://github.com/javierjulio/activeadmin/blob/ff06447047aa2d49a03da2c5d23ec48d6c08f9b9/config/locales/en.yml#L129-L132 What do you think @deivid-rodriguez and @varyonic?

**Comment by humancopy** [comment]
@javierjulio I don't mind doing the same on that branch if that's what you meant? :smile:

@varyonic I'd be happy to help make RTL work properly, but if @javierjulio is doing an overhaul on the CSS maybe it's better to do it on his branch?

**Comment by deivid-rodriguez** [comment]
I'd say let's take the chance to extract that change in the copy to a separate PR. Get that reviewed & merged. And then let @humancopy rebase this PR and translate the new copy. Makes sense?

**Comment by deivid-rodriguez** [comment]
Hi @humancopy!! We've changed the outdated browser message copy. Could you rebase this PR and translate it into Hebrew?

**Comment by humancopy** [comment]
Rebase and translation done ... Let me know how you guys would like to continue with RTL support. I didn't look at what was done until now, but maybe it's better to start afresh?

**Comment by deivid-rodriguez** [comment]
@humancopy It's really up to you. I had a look at the branch and it has a very few changes. I would suggest that you review the changes and pick whatever you find useful!

Thanks for picking up on RTL, for the translations and for updating the links!

**Pull request merged**
