### PR TITLE
Search status improvements

### PR DESCRIPTION
**Pull request by vitalinfo**
Dates predicates translation added
Fix "Current filters" titles list
Add filter translation if exist

### CODE REVIEW

**Comment by dymio** [comment]
I've found a bug and wanted to send new pull request but found that this PR fixing the bug.

It's about line 19 in lib/active_admin/filters/active.rb file — without adding `@params["q"]` search status always shows no filters active.

**Comment by Fivell** [comment]
@dymio , what is you'r AA version ?

**Comment by dymio** [comment]
@Fivell activeadmin 1.0.0.pre4, rails 4.2.8, ruby ruby-2.2.3.

**Comment by Fivell** [comment]
@dymio , try  1.0.0.pre5

**Comment by dymio** [comment]
@Fivell it helped. Thank you. I've missed information about new pre-release, sorry.

Hope params will always be a HashWithIndifferentAccess because method `to_unsafe_h` drops ability to take values by symbol. I have checked it, maybe it will help you:

```
(byebug) params
{"utf8"=>"✓", "q"=>{"hided_eq"=>"false"}, "commit"=>"Фильтровать", "order"=>"published_at_desc", "controller"=>"news", "action"=>"index"}
(byebug) params[:q]
{"hided_eq"=>"false"}
(byebug) params['q']
{"hided_eq"=>"false"}
(byebug) up = params.to_unsafe_h
{"utf8"=>"✓", "q"=>{"hided_eq"=>"false"}, "commit"=>"Фильтровать", "order"=>"published_at_desc", "controller"=>"news", "action"=>"index"}
(byebug) up[:q]
nil
(byebug) up['q']
{"hided_eq"=>"false"}
```

**Comment by Fivell** [comment]
@dymio , if something doesn't work you're welcome to create an issue

**Comment by Fivell** [comment]
closing this since most of this was fixed in another PRs

**Pull request closed without merging**
