### PR TITLE
remove features/symbol_leak.feature

### PR DESCRIPTION
**Pull request by Fivell**
we don't need this because we drop support for ruby < 2.2.0
more details https://bugs.ruby-lang.org/issues/9634

### CODE REVIEW

**Comment by timoschilling** [comment]
I think we can remove some more things: https://github.com/activeadmin/activeadmin/commit/ece825af732a3ea86519bc8e942233145442841f#diff-ce434c523c08f60658c032379f82f3b1

**Comment by Fivell** [comment]
@timoschilling , you're right thanks

**Comment by Fivell** [comment]
@timoschilling , take a look now

**Comment by Fivell** [comment]
@activeadmin/collaborators , rebased

**Pull request merged**
