### PR TITLE
4128 add indonesian translations

### PR DESCRIPTION
**Pull request by saveav**
Adding support for Indonesian translation/locale in ActiveAdmin

### CODE REVIEW

**Comment by timoschilling** [comment]
I can't accept this PR, provide it only with the locale change

**Comment by saveav** [comment]
@timoschilling OK, I can force push it

**Comment by saveav** [comment]
Hi @timoschilling, I already made the changes. But part of the test failed, due to RAILS 3.

**Comment by timoschilling** [comment]
The Rails 3 test don't fail because of your change, every thing is fine with you PR now

**Pull request merged**
