### PR TITLE
Add a skip-comments flag for the install generator

### LINKED ISSUE #5322: skip-comments flag on install
Most of the time, when using AA, I don't use comments. Right now, whenever I add AA to a project, I have to go back and delete the migration and add `ActiveAdmin.setup { |config| config.comments = false }` to my initializer. It'd be nice to have a way to disable have these steps done for me automatically with a command-line flag

### Expected behavior

`rails g active_admin:install --skip-comments` would prevent the migration from being created, and it would set `comments = false` in the initializer config.

### Actual behavior

`--skip-comments` is not a supported flag.

### PR DESCRIPTION
**Pull request by dkniffin**
Resolves #5322

### CODE REVIEW

**Comment by dkniffin** [comment]
Thanks guys!

**Comment by dkniffin** [comment]
@varyonic @Fivell Any chance I can get a patch version bump for this? I'd like to start using it, without having to link to my fork.

**Comment by varyonic** [comment]
It'll cost you a beer or coffee next time I'm in Durham.  Good to see SB using AA.

**Comment by dkniffin** [comment]
@varyonic did you work with SB at some point?

**Pull request merged**
