### PR TITLE
Remove iconic

### PR DESCRIPTION
**Pull request by timoschilling**
ref: #3399, #3451

Changelog and backport how to will follow

### CODE REVIEW

**Comment by javierjulio** [comment]
Great that we are dropping this but I'm not sure font icons are the best way to go. I think it was good to ditch Iconic for another solution but I get the feeling SVG will be the better way going forward. Although when I did a search on this recently, seems hard to find a library with SVG icons (at least one that is free/open source).

**Comment by timoschilling** [comment]
I think in the future ActiveAdmin will not support Icons natively, the old way was creepy and works only on a few places and I thing we should not build in a new way.

I have described a possible new way in https://github.com/activeadmin/activeadmin/issues/3399#issuecomment-91053676.

**Comment by seanlinsley** [comment]
I don't think this should be in 1.0.0. It's a breaking change that causes unnecessary pain.

**Comment by timoschilling** [comment]
@seanlinsley it's gone since over halve a year. A 1.0.0 means that there is a breaking change! You can put them into a separate gem.

**Comment by seanlinsley** [comment]
It's a breaking change with no replacement. I think this should wait until we have a suitable replacement. Until then, you're causing unnecessary pain for people who try upgrading.

**Comment by seanlinsley** [comment]
It's fine if this stays on master, but I think the official 1.0.0 release on Rubygems shouldn't include it.

**Comment by seanlinsley** [comment]
I'd have a different opinion if we had a replacement ready for the 1.0.0 release (which I'd like to get out in the next month or so).

**Comment by timoschilling** [comment]
I think we should not have a replacement, if some want Icons he can use fontawesome & co

**Comment by javierjulio** [comment]
Yes I'm with @timoschilling on this. Until we can get a theme into the app that is easily configurable in a lot of areas this should be best left out and let users add them as they want it. Or a solution that can be easily turned off and not included if someone wants to use their own library. We should worry less about including heavy defaults and let users add their own without having bulk.

**Pull request merged**
