### PR TITLE
Update russian locale

### PR DESCRIPTION
**Pull request by davydovanton**
:sparkler:

### CODE REVIEW

**Comment by timoschilling** [comment]
There is a misstage in your change:
```yaml
turn_off_compatibility_view: "If you are using IE 9 or later, make sure you <a href=\"http://windows.microsoft.com/en-US/windows7/webpages-look-incorrect-in-Internet-Explorer\">turn off \"Compatibility View\"</a>."
turn_off_compatibility_view: "Если вы используете IE 9 или новее, убедитесь, что <a href=\"http://windows.microsoft.com/en-US/windows7/webpages-look-incorrect-in-Internet-Explorer\">вы выключили опцию \"Просмотр в режиме совместимости\"</a>."
```
You have left the english version in your russian version

**Comment by timoschilling** [comment]
And please don't use [skip ci] for locale changes, we have some specs for the locales

**Comment by davydovanton** [comment]
ups, sorry, I need more sleep :sweat:
Delete excess line and change commit message

**Comment by davydovanton** [comment]
thanks! :tada:

**Pull request merged**
