### PR TITLE
Recommend `inherited_resources` "official" repo

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
It seems like it has an extra fix that's not in the fork...

### CODE REVIEW

**Comment by timoschilling** [comment]
Thanks for the hint on the new commits, but I will keep the reference at our own fork, so we can apply new fixes until a new version of inherited_resources is released. I have pulled from the josevalim/inherited_resources repo and pushed to activeadmin/inherited_resources

**Comment by deivid-rodriguez** [comment]
You're welcome. I disagree with tracking a fork by default, specially when it's less active than the official repo.

However, I think the best solution would be to transfer the `inherited_resources` repository to the `activeadmin` organization since it seems to be the most popular project still stuck with it. I think the current owners would agree with this since they consider it a legacy project, and you would get privileges and be able to release the gem yourselves. What do you think? Should we ping Rafael França?

**Comment by varyonic** [comment]
FYI see also #3604 and #3193 and [IR#415](https://github.com/josevalim/inherited_resources/issues/415) I think ActiveAdmin organization maintaining a fork is a good compromise.

**Comment by deivid-rodriguez** [comment]
Another option is to just vendor whatever code from inherited_resources activeadmin is depending on.

**Comment by deivid-rodriguez** [comment]
The problem with the fork is that you can't release to rubygems unless you rename the gem. And you most likely want a release before 1.0.0.

**Comment by varyonic** [comment]
Agreed.  I propose emailing the current owners of inherited resources (Jose, Rafael and Georges) and requesting (a) that one or more of us be [added as an owner](http://stackoverflow.com/questions/8487218/how-to-add-more-owners-to-a-gem-in-rubygem) of the inherited_resources gem on rubygems, and (b) that the original inherited_resources repository be transferred to activeadmin.  If we cannot have (b) then we continue to maintain our own fork, and if we cannot have (a) then we publish our fork with the name inherited_resoures_lts (long term support)
or some such.

**Comment by deivid-rodriguez** [comment]
Sounds good to me. Except maybe for the case where you're forced to release a differently named gem. In that case, I'd consider vendoring. But let's worry about that only when/if that happens.

**Comment by varyonic** [comment]
@timoschilling Are you willing to accept the original inherited_resources repo into activeadmin organization if @josevalim is willing to transfer it?

**Comment by deivid-rodriguez** [comment]
So the repo was actually transferred, right? :tada: Did you also get rubygems' permissions, @timoschilling?

**Comment by varyonic** [comment]
@deivid-rodriguez Yes. You can see the new owner on [rubygems](https://rubygems.org/gems/inherited_resources)

**Comment by deivid-rodriguez** [comment]
Cooool.

**Pull request closed without merging**
