### PR TITLE
prepare for release 1.1.0

### PR DESCRIPTION
**Pull request by Fivell**

### CODE REVIEW

**Comment by javierjulio** [comment]
We should make sure we have changelog items for anything else we did in v1.1. Do we want to mention any of it? A lot of internal stuff so probably unnecessary.

**Comment by deivid-rodriguez** [comment]
@javierjulio I did it in #5077. Basically documenting some of the awesome @Fivell's work that had not been included.

**Comment by Fivell** [comment]
@javierjulio , I'll rebase

**Comment by fredngo** [comment]
Congrats on the 1.1.0 Release!!!!

**Pull request merged**
