### PR TITLE
Removes docs from exported gem

### PR DESCRIPTION
**Pull request by brunoarueira**
It's useful to shrink the gem a little bit and normally is better to
read online docs

### CODE REVIEW

**Comment by javierjulio** [comment]
I will accept this change once CI is green. I will rebase and push.

**Comment by javierjulio** [comment]
@brunoarueira I'm not sure what went wrong with the branch update but if you could interactive rebase or just throw an empty commit here to re-run CI, I'd appreciate it.

**Comment by brunoarueira** [comment]
> @brunoarueira I'm not sure what went wrong with the branch update but if you could interactive rebase or just throw an empty commit here to re-run CI, I'd appreciate it.

@javierjulio done dde80c0

**Comment by javierjulio** [comment]
Thank you!

**Pull request merged**
