### PR TITLE
dynamic respond_to in ResourceController

### PR DESCRIPTION
**Pull request by timoschilling**
this is a fix for #3539

befor this change, AA respond to html, xml and json on each action, that's a securty problem while the user can view a record as xml and see the raw data.

after this change AA respond only to html on each action and respond to xml, csv, json only it the format is configured for the download links.

Now a user can only see that data he has access to

### CODE REVIEW

**Comment by seanlinsley** [comment]
This PR is nearly a year old, and is still missing tests. While it would be nice to limit download links based on the user's permissions, this isn't the right approach. Instead it should be limited by `ActiveAdmin::AuthorizationAdapter`.

@timoschilling if you still plan to work on this PR, feel free to reopen.

**Comment by timoschilling** [comment]
We should keep this open, while it provides a solution. The age isn't necessary, we have PR's that are older.

**Comment by vraravam** [comment]
hi - I am looking for this exact solution: just hiding the download links does not work, I need to be able to un-authorize a user if their role does not allow to actually download CSVs, etc. Could this be merged soon?

**Comment by dmitry** [comment]
@vraravam once it will be updated with tests and auth changes - it will be merged.

**Comment by Fivell** [comment]
@timoschilling , I think this PR is worth rebasing

**Comment by timoschilling** [comment]
@Fivell feel free to continue the work on this

**Pull request closed without merging**
