### PR TITLE
[wip] Rails 5 Bug Report Template

### PR DESCRIPTION
**Pull request by ccallebs**
Attempts to address activeadmin/activeadmin#4782. Currently not working -- having issues with view rendering during specs. It took quite a bit of work to figure out the dependency issues and this was a sloppy first pass. I'm sure that I can remove a lot of the cludge if I can figure out how to ensure the load order for the gems.

With all that being said, I'd like to open this up for discussion / debugging.

### CODE REVIEW

**Comment by Fivell** [comment]
@ccallebs , what kind of issues with view rendering  ?

**Comment by ccallebs** [comment]
@Fivell Specifically:

```
# Running:

I, [2017-02-09T10:24:05.561772 #54353]  INFO -- : Started GET "/admin" for 127.0.0.1 at 2017-02-09 10:24:05 -0500
F, [2017-02-09T10:24:05.575895 #54353] FATAL -- :
F, [2017-02-09T10:24:05.575941 #54353] FATAL -- : ActionView::MissingTemplate (Missing template active_admin/page/index with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :arb, :coffee]}. Searched in:
):
F, [2017-02-09T10:24:05.575959 #54353] FATAL -- :
F, [2017-02-09T10:24:05.575971 #54353] FATAL -- : lib/bug_report_templates/rails_5.rb:139:in `test_returns_success?'
F

Finished in 0.088313s, 11.3233 runs/s, 11.3233 assertions/s.

  1) Failure:
BugTest#test_returns_success? [lib/bug_report_templates/rails_5.rb:140]:
Expected false to be truthy.

1 runs, 1 assertions, 1 failures, 0 errors, 0 skips
```

**Comment by senid231** [comment]
i fix this and remove obsolete parts
take a look at #4790

**Comment by deivid-rodriguez** [comment]
@ccallebs Are you fine with closing this and continue work in #4790?

**Comment by ccallebs** [comment]
@deivid-rodriguez Closing this now.

**Pull request closed without merging**
